// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    contact: {
      name: 'Google',
      url: 'https://google.com',
      'x-twitter': 'youtube',
    },
    description:
      'Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.',
    license: {
      name: 'Creative Commons Attribution 3.0',
      url: 'http://creativecommons.org/licenses/by/3.0/',
    },
    termsOfService: 'https://developers.google.com/terms/',
    title: 'Drive API',
    version: 'v3',
    'x-apiClientRegistration': {url: 'https://console.developers.google.com'},
    'x-apisguru-categories': ['analytics', 'media'],
    'x-logo': {
      url: 'https://api.apis.guru/v2/cache/logo/https_www.google.com_images_branding_googlelogo_2x_googlelogo_color_272x92dp.png',
    },
    'x-origin': [
      {
        converter: {
          url: 'https://github.com/mermade/oas-kit',
          version: '7.0.4',
        },
        format: 'google',
        url: 'https://www.googleapis.com/discovery/v1/apis/drive/v3/rest',
        version: 'v1',
      },
    ],
    'x-preferred': true,
    'x-providerName': 'googleapis.com',
    'x-serviceName': 'drive',
  },
  servers: [{url: 'https://www.googleapis.com/drive/v3'}],
} as const
export default oasMeta
