// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {title: 'Nango API', version: '0.0.0'},
  servers: [{url: 'https://api.nango.dev'}],
} as const
export default oasMeta
