/**
 * This file was generated by @opensdks/cli, do not edit manually.
 * For bugs & feature requests, please open an issue on the [GitHub](https://github.com/tonyxiao/openSDKs)
 */

import type {
  ClientOptions,
  OpenAPITypes,
  SdkDefinition,
  SDKTypes,
} from '@opensdks/runtime'
import {initSDK} from '@opensdks/runtime'
import type Oas_experience_api_v2 from '../onebrick_experience_api_v2.oas.types.js'
import type Oas_payment_v2_auth_v2 from '../onebrick_payment_v2_auth_v2.oas.types.js'
import type Oas_payment_v2_base_url_v2 from '../onebrick_payment_v2_base_url_v2.oas.types.js'
import type Oas_payment_v2_v2 from '../onebrick_payment_v2_v2.oas.types.js'
import type Oas_sanbox_get_token_v1_collection_v1 from '../onebrick_sanbox_get_token_v1_collection_v1.oas.types.js'
import type Oas_sandbox_payment_v_1_1_collection_v1 from '../onebrick_sandbox_payment_v_1_1_collection_v1.oas.types.js'
import type Oas_sandbox_v1_collection_v1 from '../onebrick_sandbox_v1_collection_v1.oas.types.js'
import type Oas_sandbox_v1_collections1_v1 from '../onebrick_sandbox_v1_collections1_v1.oas.types.js'
import type Oas_sandbox_v2_data_collection_v2 from '../onebrick_sandbox_v2_data_collection_v2.oas.types.js'
import {default as oas_experience_api_v2} from './onebrick_experience_api_v2.oas.meta.js'
import {default as oas_payment_v2_auth_v2} from './onebrick_payment_v2_auth_v2.oas.meta.js'
import {default as oas_payment_v2_base_url_v2} from './onebrick_payment_v2_base_url_v2.oas.meta.js'
import {default as oas_payment_v2_v2} from './onebrick_payment_v2_v2.oas.meta.js'
import {default as oas_sanbox_get_token_v1_collection_v1} from './onebrick_sanbox_get_token_v1_collection_v1.oas.meta.js'
import {default as oas_sandbox_payment_v_1_1_collection_v1} from './onebrick_sandbox_payment_v_1_1_collection_v1.oas.meta.js'
import {default as oas_sandbox_v1_collection_v1} from './onebrick_sandbox_v1_collection_v1.oas.meta.js'
import {default as oas_sandbox_v1_collections1_v1} from './onebrick_sandbox_v1_collections1_v1.oas.meta.js'
import {default as oas_sandbox_v2_data_collection_v2} from './onebrick_sandbox_v2_data_collection_v2.oas.meta.js'

export type {
  Oas_experience_api_v2,
  Oas_payment_v2_auth_v2,
  Oas_payment_v2_base_url_v2,
  Oas_payment_v2_v2,
  Oas_sanbox_get_token_v1_collection_v1,
  Oas_sandbox_payment_v_1_1_collection_v1,
  Oas_sandbox_v1_collection_v1,
  Oas_sandbox_v1_collections1_v1,
  Oas_sandbox_v2_data_collection_v2,
}

export {
  oas_experience_api_v2,
  oas_payment_v2_auth_v2,
  oas_payment_v2_base_url_v2,
  oas_payment_v2_v2,
  oas_sanbox_get_token_v1_collection_v1,
  oas_sandbox_payment_v_1_1_collection_v1,
  oas_sandbox_v1_collection_v1,
  oas_sandbox_v1_collections1_v1,
  oas_sandbox_v2_data_collection_v2,
}

export type OnebrickSDKTypes = SDKTypes<OpenAPITypes, ClientOptions>

export const onebrickSdkDef = {
  types: {} as OnebrickSDKTypes,
  defaultOptions: {},
  createClient(ctx, options) {
    const experience_api_v2 = ctx.createClient<Oas_experience_api_v2['paths']>({
      ...options,
      baseUrl: options.baseUrl ?? oas_experience_api_v2.servers[0]?.url,
    })
    const payment_v2_auth_v2 = ctx.createClient<
      Oas_payment_v2_auth_v2['paths']
    >({
      ...options,
      baseUrl: options.baseUrl ?? oas_payment_v2_auth_v2.servers[0]?.url,
    })
    const payment_v2_base_url_v2 = ctx.createClient<
      Oas_payment_v2_base_url_v2['paths']
    >({
      ...options,
      baseUrl: options.baseUrl ?? oas_payment_v2_base_url_v2.servers[0]?.url,
    })
    const payment_v2_v2 = ctx.createClient<Oas_payment_v2_v2['paths']>({
      ...options,
      baseUrl: options.baseUrl ?? oas_payment_v2_v2.servers[0]?.url,
    })
    const sanbox_get_token_v1_collection_v1 = ctx.createClient<
      Oas_sanbox_get_token_v1_collection_v1['paths']
    >({
      ...options,
      baseUrl:
        options.baseUrl ??
        oas_sanbox_get_token_v1_collection_v1.servers[0]?.url,
    })
    const sandbox_payment_v_1_1_collection_v1 = ctx.createClient<
      Oas_sandbox_payment_v_1_1_collection_v1['paths']
    >({
      ...options,
      baseUrl:
        options.baseUrl ??
        oas_sandbox_payment_v_1_1_collection_v1.servers[0]?.url,
    })
    const sandbox_v1_collection_v1 = ctx.createClient<
      Oas_sandbox_v1_collection_v1['paths']
    >({
      ...options,
      baseUrl: options.baseUrl ?? oas_sandbox_v1_collection_v1.servers[0]?.url,
    })
    const sandbox_v1_collections1_v1 = ctx.createClient<
      Oas_sandbox_v1_collections1_v1['paths']
    >({
      ...options,
      baseUrl:
        options.baseUrl ?? oas_sandbox_v1_collections1_v1.servers[0]?.url,
    })
    const sandbox_v2_data_collection_v2 = ctx.createClient<
      Oas_sandbox_v2_data_collection_v2['paths']
    >({
      ...options,
      baseUrl:
        options.baseUrl ?? oas_sandbox_v2_data_collection_v2.servers[0]?.url,
    })

    return {
      experience_api_v2,
      payment_v2_auth_v2,
      payment_v2_base_url_v2,
      payment_v2_v2,
      sanbox_get_token_v1_collection_v1,
      sandbox_payment_v_1_1_collection_v1,
      sandbox_v1_collection_v1,
      sandbox_v1_collections1_v1,
      sandbox_v2_data_collection_v2,
    }
  },
} satisfies SdkDefinition<OnebrickSDKTypes>

export function initOnebrickSDK(opts: OnebrickSDKTypes['options']) {
  return initSDK(onebrickSdkDef, opts)
}

export type OnebrickSDK = ReturnType<typeof initOnebrickSDK>

export default initOnebrickSDK
