// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {title: 'Payment v2 Auth', version: '2'},
  servers: [{url: 'https://sandbox.onebrick.io/v2/payments'}],
} as const
export default oasMeta
