// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    version: '1.1.4',
    title: 'GitHub v3 REST API',
    description: "GitHub's v3 REST API.",
    license: {name: 'MIT', url: 'https://spdx.org/licenses/MIT'},
    termsOfService: 'https://docs.github.com/articles/github-terms-of-service',
    contact: {
      name: 'Support',
      url: 'https://support.github.com/contact?tags=dotcom-rest-api',
    },
    'x-github-plan': 'api.github.com',
  },
  servers: [{url: 'https://api.github.com'}],
} as const
export default oasMeta
