// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    title: 'Twenty Api',
    description:
      'This is a **Twenty REST/API** playground based on the **OpenAPI 3.0 specification**.',
    termsOfService: 'https://github.com/twentyhq/twenty?tab=coc-ov-file',
    contact: {email: 'felix@twenty.com'},
    license: {
      name: 'AGPL-3.0',
      url: 'https://github.com/twentyhq/twenty?tab=AGPL-3.0-1-ov-file#readme',
    },
    version: '0.2.0',
  },
  servers: [
    {
      url: 'https://api.twenty.com/rest/',
      description: 'Production Development',
    },
  ],
} as const
export default oasMeta
