/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/v1/Services/{ServiceSid}/AlphaSenders': {
    get: operations['ListAlphaSender']
    post: operations['CreateAlphaSender']
  }
  '/v1/Services/{ServiceSid}/AlphaSenders/{Sid}': {
    get: operations['FetchAlphaSender']
    delete: operations['DeleteAlphaSender']
  }
  '/v1/a2p/BrandRegistrations/{BrandRegistrationSid}/SmsOtp': {
    post: operations['CreateBrandRegistrationOtp']
  }
  '/v1/a2p/BrandRegistrations/{Sid}': {
    get: operations['FetchBrandRegistrations']
    post: operations['UpdateBrandRegistrations']
  }
  '/v1/a2p/BrandRegistrations': {
    get: operations['ListBrandRegistrations']
    post: operations['CreateBrandRegistrations']
  }
  '/v1/a2p/BrandRegistrations/{BrandSid}/Vettings': {
    get: operations['ListBrandVetting']
    post: operations['CreateBrandVetting']
  }
  '/v1/a2p/BrandRegistrations/{BrandSid}/Vettings/{BrandVettingSid}': {
    get: operations['FetchBrandVetting']
  }
  '/v1/Services/{MessagingServiceSid}/ChannelSenders': {
    get: operations['ListChannelSender']
  }
  '/v1/Services/{MessagingServiceSid}/ChannelSenders/{Sid}': {
    get: operations['FetchChannelSender']
  }
  '/v1/Deactivations': {
    /** @description Fetch a list of all United States numbers that have been deactivated on a specific date. */
    get: operations['FetchDeactivation']
  }
  '/v1/LinkShortening/Domains/{DomainSid}/Certificate': {
    get: operations['FetchDomainCertV4']
    post: operations['UpdateDomainCertV4']
    delete: operations['DeleteDomainCertV4']
  }
  '/v1/LinkShortening/Domains/{DomainSid}/Config': {
    get: operations['FetchDomainConfig']
    post: operations['UpdateDomainConfig']
  }
  '/v1/LinkShortening/MessagingService/{MessagingServiceSid}/DomainConfig': {
    get: operations['FetchDomainConfigMessagingService']
  }
  '/v1/Services/PreregisteredUsa2p': {
    post: operations['CreateExternalCampaign']
  }
  '/v1/LinkShortening/Domains/{DomainSid}/MessagingServices/{MessagingServiceSid}': {
    post: operations['CreateLinkshorteningMessagingService']
    delete: operations['DeleteLinkshorteningMessagingService']
  }
  '/v1/LinkShortening/MessagingServices/{MessagingServiceSid}/Domain': {
    get: operations['FetchLinkshorteningMessagingServiceDomainAssociation']
  }
  '/v1/Services/{ServiceSid}/PhoneNumbers': {
    get: operations['ListPhoneNumber']
    post: operations['CreatePhoneNumber']
  }
  '/v1/Services/{ServiceSid}/PhoneNumbers/{Sid}': {
    get: operations['FetchPhoneNumber']
    delete: operations['DeletePhoneNumber']
  }
  '/v1/Services': {
    get: operations['ListService']
    post: operations['CreateService']
  }
  '/v1/Services/{Sid}': {
    get: operations['FetchService']
    post: operations['UpdateService']
    delete: operations['DeleteService']
  }
  '/v1/Services/{ServiceSid}/ShortCodes': {
    get: operations['ListShortCode']
    post: operations['CreateShortCode']
  }
  '/v1/Services/{ServiceSid}/ShortCodes/{Sid}': {
    get: operations['FetchShortCode']
    delete: operations['DeleteShortCode']
  }
  '/v1/Tollfree/Verifications/{Sid}': {
    get: operations['FetchTollfreeVerification']
    post: operations['UpdateTollfreeVerification']
    delete: operations['DeleteTollfreeVerification']
  }
  '/v1/Tollfree/Verifications': {
    get: operations['ListTollfreeVerification']
    post: operations['CreateTollfreeVerification']
  }
  '/v1/Services/{MessagingServiceSid}/Compliance/Usa2p': {
    get: operations['ListUsAppToPerson']
    post: operations['CreateUsAppToPerson']
  }
  '/v1/Services/{MessagingServiceSid}/Compliance/Usa2p/{Sid}': {
    get: operations['FetchUsAppToPerson']
    delete: operations['DeleteUsAppToPerson']
  }
  '/v1/Services/{MessagingServiceSid}/Compliance/Usa2p/Usecases': {
    get: operations['FetchUsAppToPersonUsecase']
  }
  '/v1/Services/Usecases': {
    get: operations['FetchUsecase']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    'messaging.v1.service.alpha_sender': {
      /** @description The unique string that we created to identify the AlphaSender resource. */
      sid?: string | null
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the AlphaSender resource. */
      account_sid?: string | null
      /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) the resource is associated with. */
      service_sid?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null
      /** @description The Alphanumeric Sender ID string. */
      alpha_sender?: string | null
      /** @description An array of values that describe whether the number can receive calls or messages. Can be: `SMS`. */
      capabilities?: string[] | null
      /**
       * Format: uri
       * @description The absolute URL of the AlphaSender resource.
       */
      url?: string | null
    }
    'messaging.v1.brand_registrations.brand_registration_otp': {
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Brand Registration resource. */
      account_sid?: string | null
      /** @description The unique string to identify Brand Registration of Sole Proprietor Brand */
      brand_registration_sid?: string | null
    }
    'messaging.v1.brand_registrations': {
      /** @description The unique string to identify Brand Registration. */
      sid?: string | null
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Brand Registration resource. */
      account_sid?: string | null
      /** @description A2P Messaging Profile Bundle BundleSid. */
      customer_profile_bundle_sid?: string | null
      /** @description A2P Messaging Profile Bundle BundleSid. */
      a2p_profile_bundle_sid?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null
      /** @description Type of brand. One of: "STANDARD", "SOLE_PROPRIETOR". SOLE_PROPRIETOR is for the low volume, SOLE_PROPRIETOR campaign use case. There can only be one SOLE_PROPRIETOR campaign created per SOLE_PROPRIETOR brand. STANDARD is for all other campaign use cases. Multiple campaign use cases can be created per STANDARD brand. */
      brand_type?: string | null
      /** @description Brand Registration status. One of "PENDING", "APPROVED", "FAILED", "IN_REVIEW", "DELETED". */
      status?: components['schemas']['brand_registrations_enum_status']
      /** @description Campaign Registry (TCR) Brand ID. Assigned only after successful brand registration. */
      tcr_id?: string | null
      /** @description A reason why brand registration has failed. Only applicable when status is FAILED. */
      failure_reason?: string | null
      /**
       * Format: uri
       * @description The absolute URL of the Brand Registration resource.
       */
      url?: string | null
      /** @description The secondary vetting score if it was done. Otherwise, it will be the brand score if it's returned from TCR. It may be null if no score is available. */
      brand_score?: number | null
      /** @description Feedback on how to improve brand score */
      brand_feedback?:
        | components['schemas']['brand_registrations_enum_brand_feedback'][]
        | null
      /** @description When a brand is registered, TCR will attempt to verify the identity of the brand based on the supplied information. */
      identity_status?: components['schemas']['brand_registrations_enum_identity_status']
      /** @description Publicly traded company identified in the Russell 3000 Index */
      russell_3000?: boolean | null
      /** @description Identified as a government entity */
      government_entity?: boolean | null
      /** @description Nonprofit organization tax-exempt status per section 501 of the U.S. tax code. */
      tax_exempt_status?: string | null
      /** @description A flag to disable automatic secondary vetting for brands which it would otherwise be done. */
      skip_automatic_sec_vet?: boolean | null
      /** @description A boolean that specifies whether brand should be a mock or not. If true, brand will be registered as a mock brand. Defaults to false if no value is provided. */
      mock?: boolean | null
      /** Format: uri-map */
      links?: unknown
    }
    /** @enum {string} */
    brand_registrations_enum_status:
      | 'PENDING'
      | 'APPROVED'
      | 'FAILED'
      | 'IN_REVIEW'
      | 'DELETED'
    /** @enum {string} */
    brand_registrations_enum_identity_status:
      | 'SELF_DECLARED'
      | 'UNVERIFIED'
      | 'VERIFIED'
      | 'VETTED_VERIFIED'
    /** @enum {string} */
    brand_registrations_enum_brand_feedback:
      | 'TAX_ID'
      | 'STOCK_SYMBOL'
      | 'NONPROFIT'
      | 'GOVERNMENT_ENTITY'
      | 'OTHERS'
    'messaging.v1.brand_registrations.brand_vetting': {
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the vetting record. */
      account_sid?: string | null
      /** @description The unique string to identify Brand Registration. */
      brand_sid?: string | null
      /** @description The Twilio SID of the third-party vetting record. */
      brand_vetting_sid?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null
      /** @description The unique identifier of the vetting from the third-party provider. */
      vetting_id?: string | null
      /** @description The type of vetting that has been conducted. One of “STANDARD” (Aegis) or “POLITICAL” (Campaign Verify). */
      vetting_class?: string | null
      /** @description The status of the import vetting attempt. One of “PENDING,” “SUCCESS,” or “FAILED”. */
      vetting_status?: string | null
      /** @description The third-party provider that has conducted the vetting. One of “CampaignVerify” (Campaign Verify tokens) or “AEGIS” (Secondary Vetting). */
      vetting_provider?: components['schemas']['brand_vetting_enum_vetting_provider']
      /**
       * Format: uri
       * @description The absolute URL of the Brand Vetting resource.
       */
      url?: string | null
    }
    /** @enum {string} */
    brand_vetting_enum_vetting_provider: 'campaign-verify'
    'messaging.v1.service.channel_sender': {
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the ChannelSender resource. */
      account_sid?: string | null
      /** @description The SID of the [Service](https://www.twilio.com/docs/messaging/services) the resource is associated with. */
      messaging_service_sid?: string | null
      /** @description The unique string that we created to identify the ChannelSender resource. */
      sid?: string | null
      /** @description The unique string that identifies the sender e.g whatsapp:+123456XXXX. */
      sender?: string | null
      /** @description A string value that identifies the sender type e.g WhatsApp, Messenger. */
      sender_type?: string | null
      /** @description The 2-character [ISO Country Code](https://www.iso.org/iso-3166-country-codes.html) of the number. */
      country_code?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null
      /**
       * Format: uri
       * @description The absolute URL of the ChannelSender resource.
       */
      url?: string | null
    }
    'messaging.v1.deactivation': {
      /**
       * Format: uri
       * @description Returns an authenticated url that redirects to a file containing the deactivated numbers for the requested day. This url is valid for up to two minutes.
       */
      redirect_to?: string | null
    }
    'messaging.v1.domain_cert_v4': {
      /** @description The unique string that we created to identify the Domain resource. */
      domain_sid?: string | null
      /**
       * Format: date-time
       * @description Date that this Domain was last updated.
       */
      date_updated?: string | null
      /**
       * Format: date-time
       * @description Date that the private certificate associated with this domain expires. You will need to update the certificate before that date to ensure your shortened links will continue to work.
       */
      date_expires?: string | null
      /**
       * Format: date-time
       * @description Date that this Domain was registered to the Twilio platform to create a new Domain object.
       */
      date_created?: string | null
      /**
       * Format: uri
       * @description Full url path for this domain.
       */
      domain_name?: string | null
      /** @description The unique string that we created to identify this Certificate resource. */
      certificate_sid?: string | null
      /** Format: uri */
      url?: string | null
      /** @description Optional JSON field describing the status and upload date of a new certificate in the process of validation */
      cert_in_validation?: unknown
    }
    'messaging.v1.domain_config': {
      /** @description The unique string that we created to identify the Domain resource. */
      domain_sid?: string | null
      /** @description The unique string that we created to identify the Domain config (prefix ZK). */
      config_sid?: string | null
      /**
       * Format: uri
       * @description Any requests we receive to this domain that do not match an existing shortened message will be redirected to the fallback url. These will likely be either expired messages, random misdirected traffic, or intentional scraping.
       */
      fallback_url?: string | null
      /**
       * Format: uri
       * @description URL to receive click events to your webhook whenever the recipients click on the shortened links.
       */
      callback_url?: string | null
      /** @description Boolean field to set customer delivery preference when there is a failure in linkShortening service */
      continue_on_failure?: boolean | null
      /**
       * Format: date-time
       * @description Date this Domain Config was created.
       */
      date_created?: string | null
      /**
       * Format: date-time
       * @description Date that this Domain Config was last updated.
       */
      date_updated?: string | null
      /** Format: uri */
      url?: string | null
      /** @description Customer's choice to send links with/without "https://" attached to shortened url. If true, messages will not be sent with https:// at the beginning of the url. If false, messages will be sent with https:// at the beginning of the url. False is the default behavior if it is not specified. */
      disable_https?: boolean | null
    }
    'messaging.v1.domain_config_messaging_service': {
      /** @description The unique string that we created to identify the Domain resource. */
      domain_sid?: string | null
      /** @description The unique string that we created to identify the Domain config (prefix ZK). */
      config_sid?: string | null
      /** @description The unique string that identifies the messaging service */
      messaging_service_sid?: string | null
      /**
       * Format: uri
       * @description Any requests we receive to this domain that do not match an existing shortened message will be redirected to the fallback url. These will likely be either expired messages, random misdirected traffic, or intentional scraping.
       */
      fallback_url?: string | null
      /**
       * Format: uri
       * @description URL to receive click events to your webhook whenever the recipients click on the shortened links.
       */
      callback_url?: string | null
      /** @description Boolean field to set customer delivery preference when there is a failure in linkShortening service */
      continue_on_failure?: boolean | null
      /**
       * Format: date-time
       * @description Date this Domain Config was created.
       */
      date_created?: string | null
      /**
       * Format: date-time
       * @description Date that this Domain Config was last updated.
       */
      date_updated?: string | null
      /** Format: uri */
      url?: string | null
    }
    'messaging.v1.external_campaign': {
      /** @description The unique string that identifies a US A2P Compliance resource `QE2c6890da8086d771620e9b13fadeba0b`. */
      sid?: string | null
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that the Campaign belongs to. */
      account_sid?: string | null
      /** @description ID of the preregistered campaign. */
      campaign_id?: string | null
      /** @description The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) that the resource is associated with. */
      messaging_service_sid?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null
    }
    'messaging.v1.linkshortening_messaging_service': {
      /** @description The unique string identifies the domain resource */
      domain_sid?: string | null
      /** @description The unique string that identifies the messaging service */
      messaging_service_sid?: string | null
      /** Format: uri */
      url?: string | null
    }
    'messaging.v1.linkshortening_messaging_service_domain_association': {
      /** @description The unique string that we created to identify the Domain resource. */
      domain_sid?: string | null
      /** @description The unique string that identifies the messaging service */
      messaging_service_sid?: string | null
      /** Format: uri */
      url?: string | null
    }
    'messaging.v1.service.phone_number': {
      /** @description The unique string that we created to identify the PhoneNumber resource. */
      sid?: string | null
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the PhoneNumber resource. */
      account_sid?: string | null
      /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) the resource is associated with. */
      service_sid?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null
      /**
       * Format: phone-number
       * @description The phone number in [E.164](https://www.twilio.com/docs/glossary/what-e164) format, which consists of a + followed by the country code and subscriber number.
       */
      phone_number?: string | null
      /** @description The 2-character [ISO Country Code](https://www.iso.org/iso-3166-country-codes.html) of the number. */
      country_code?: string | null
      /** @description An array of values that describe whether the number can receive calls or messages. Can be: `Voice`, `SMS`, and `MMS`. */
      capabilities?: string[] | null
      /**
       * Format: uri
       * @description The absolute URL of the PhoneNumber resource.
       */
      url?: string | null
    }
    'messaging.v1.service': {
      /** @description The unique string that we created to identify the Service resource. */
      sid?: string | null
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Service resource. */
      account_sid?: string | null
      /** @description The string that you assigned to describe the resource. */
      friendly_name?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null
      /**
       * Format: uri
       * @description The URL we call using `inbound_method` when a message is received by any phone number or short code in the Service. When this property is `null`, receiving inbound messages is disabled. All messages sent to the Twilio phone number or short code will not be logged and received on the Account. If the `use_inbound_webhook_on_number` field is enabled then the webhook url defined on the phone number will override the `inbound_request_url` defined for the Messaging Service.
       */
      inbound_request_url?: string | null
      /**
       * Format: http-method
       * @description The HTTP method we use to call `inbound_request_url`. Can be `GET` or `POST`.
       * @enum {string|null}
       */
      inbound_method?:
        | 'HEAD'
        | 'GET'
        | 'POST'
        | 'PATCH'
        | 'PUT'
        | 'DELETE'
        | null
      /**
       * Format: uri
       * @description The URL that we call using `fallback_method` if an error occurs while retrieving or executing the TwiML from the Inbound Request URL. If the `use_inbound_webhook_on_number` field is enabled then the webhook url defined on the phone number will override the `fallback_url` defined for the Messaging Service.
       */
      fallback_url?: string | null
      /**
       * Format: http-method
       * @description The HTTP method we use to call `fallback_url`. Can be: `GET` or `POST`.
       * @enum {string|null}
       */
      fallback_method?:
        | 'HEAD'
        | 'GET'
        | 'POST'
        | 'PATCH'
        | 'PUT'
        | 'DELETE'
        | null
      /**
       * Format: uri
       * @description The URL we call to [pass status updates](https://www.twilio.com/docs/sms/api/message-resource#message-status-values) about message delivery.
       */
      status_callback?: string | null
      /** @description Whether to enable [Sticky Sender](https://www.twilio.com/docs/messaging/services#sticky-sender) on the Service instance. */
      sticky_sender?: boolean | null
      /** @description Whether to enable the [MMS Converter](https://www.twilio.com/docs/messaging/services#mms-converter) for messages sent through the Service instance. */
      mms_converter?: boolean | null
      /** @description Whether to enable [Smart Encoding](https://www.twilio.com/docs/messaging/services#smart-encoding) for messages sent through the Service instance. */
      smart_encoding?: boolean | null
      /** @description Reserved. */
      scan_message_content?: components['schemas']['service_enum_scan_message_content']
      /** @description [OBSOLETE] Former feature used to fallback to long code sender after certain short code message failures. */
      fallback_to_long_code?: boolean | null
      /** @description Whether to enable [Area Code Geomatch](https://www.twilio.com/docs/messaging/services#area-code-geomatch) on the Service Instance. */
      area_code_geomatch?: boolean | null
      /** @description Reserved. */
      synchronous_validation?: boolean | null
      /** @description How long, in seconds, messages sent from the Service are valid. Can be an integer from `1` to `14,400`. */
      validity_period?: number | null
      /**
       * Format: uri
       * @description The absolute URL of the Service resource.
       */
      url?: string | null
      /**
       * Format: uri-map
       * @description The absolute URLs of related resources.
       */
      links?: unknown
      /** @description A string that describes the scenario in which the Messaging Service will be used. Possible values are `notifications`, `marketing`, `verification`, `discussion`, `poll`, `undeclared`. */
      usecase?: string | null
      /** @description Whether US A2P campaign is registered for this Service. */
      us_app_to_person_registered?: boolean | null
      /** @description A boolean value that indicates either the webhook url configured on the phone number will be used or `inbound_request_url`/`fallback_url` url will be called when a message is received from the phone number. If this field is enabled then the webhook url defined on the phone number will override the `inbound_request_url`/`fallback_url` defined for the Messaging Service. */
      use_inbound_webhook_on_number?: boolean | null
    }
    /** @enum {string} */
    service_enum_scan_message_content: 'inherit' | 'enable' | 'disable'
    'messaging.v1.service.short_code': {
      /** @description The unique string that we created to identify the ShortCode resource. */
      sid?: string | null
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the ShortCode resource. */
      account_sid?: string | null
      /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) the resource is associated with. */
      service_sid?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null
      /** @description The [E.164](https://www.twilio.com/docs/glossary/what-e164) format of the short code. */
      short_code?: string | null
      /** @description The 2-character [ISO Country Code](https://www.iso.org/iso-3166-country-codes.html) of the number. */
      country_code?: string | null
      /** @description An array of values that describe whether the number can receive calls or messages. Can be: `SMS` and `MMS`. */
      capabilities?: string[] | null
      /**
       * Format: uri
       * @description The absolute URL of the ShortCode resource.
       */
      url?: string | null
    }
    'messaging.v1.tollfree_verification': {
      /** @description The unique string to identify Tollfree Verification. */
      sid?: string | null
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Tollfree Verification resource. */
      account_sid?: string | null
      /** @description Customer's Profile Bundle BundleSid. */
      customer_profile_sid?: string | null
      /** @description Tollfree TrustProduct Bundle BundleSid. */
      trust_product_sid?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null
      /** @description The SID of the Regulated Item. */
      regulated_item_sid?: string | null
      /** @description The name of the business or organization using the Tollfree number. */
      business_name?: string | null
      /** @description The address of the business or organization using the Tollfree number. */
      business_street_address?: string | null
      /** @description The address of the business or organization using the Tollfree number. */
      business_street_address2?: string | null
      /** @description The city of the business or organization using the Tollfree number. */
      business_city?: string | null
      /** @description The state/province/region of the business or organization using the Tollfree number. */
      business_state_province_region?: string | null
      /** @description The postal code of the business or organization using the Tollfree number. */
      business_postal_code?: string | null
      /** @description The country of the business or organization using the Tollfree number. */
      business_country?: string | null
      /** @description The website of the business or organization using the Tollfree number. */
      business_website?: string | null
      /** @description The first name of the contact for the business or organization using the Tollfree number. */
      business_contact_first_name?: string | null
      /** @description The last name of the contact for the business or organization using the Tollfree number. */
      business_contact_last_name?: string | null
      /** @description The email address of the contact for the business or organization using the Tollfree number. */
      business_contact_email?: string | null
      /**
       * Format: phone-number
       * @description The phone number of the contact for the business or organization using the Tollfree number.
       */
      business_contact_phone?: string | null
      /** @description The email address to receive the notification about the verification result. . */
      notification_email?: string | null
      /** @description The category of the use case for the Tollfree Number. List as many are applicable.. */
      use_case_categories?: string[] | null
      /** @description Use this to further explain how messaging is used by the business or organization. */
      use_case_summary?: string | null
      /** @description An example of message content, i.e. a sample message. */
      production_message_sample?: string | null
      /** @description Link to an image that shows the opt-in workflow. Multiple images allowed and must be a publicly hosted URL. */
      opt_in_image_urls?: string[] | null
      /** @description Describe how a user opts-in to text messages. */
      opt_in_type?: components['schemas']['tollfree_verification_enum_opt_in_type']
      /** @description Estimate monthly volume of messages from the Tollfree Number. */
      message_volume?: string | null
      /** @description Additional information to be provided for verification. */
      additional_information?: string | null
      /** @description The SID of the Phone Number associated with the Tollfree Verification. */
      tollfree_phone_number_sid?: string | null
      /** @description The compliance status of the Tollfree Verification record. */
      status?: components['schemas']['tollfree_verification_enum_status']
      /**
       * Format: uri
       * @description The absolute URL of the Tollfree Verification resource.
       */
      url?: string | null
      /** @description The rejection reason given when a Tollfree Verification has been rejected. */
      rejection_reason?: string | null
      /** @description The error code given when a Tollfree Verification has been rejected. */
      error_code?: number | null
      /**
       * Format: date-time
       * @description The date and time when the ability to edit a rejected verification expires.
       */
      edit_expiration?: string | null
      /** @description If a rejected verification is allowed to be edited/resubmitted. Some rejection reasons allow editing and some do not. */
      edit_allowed?: boolean | null
      /** @description The URLs of the documents associated with the Tollfree Verification resource. */
      resource_links?: unknown
      /** @description An optional external reference ID supplied by customer and echoed back on status retrieval. */
      external_reference_id?: string | null
    }
    /** @enum {string} */
    tollfree_verification_enum_status:
      | 'PENDING_REVIEW'
      | 'IN_REVIEW'
      | 'TWILIO_APPROVED'
      | 'TWILIO_REJECTED'
    /** @enum {string} */
    tollfree_verification_enum_opt_in_type:
      | 'VERBAL'
      | 'WEB_FORM'
      | 'PAPER_FORM'
      | 'VIA_TEXT'
      | 'MOBILE_QR_CODE'
    'messaging.v1.service.us_app_to_person': {
      /** @description The unique string that identifies a US A2P Compliance resource `QE2c6890da8086d771620e9b13fadeba0b`. */
      sid?: string | null
      /** @description The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that the Campaign belongs to. */
      account_sid?: string | null
      /** @description The unique string to identify the A2P brand. */
      brand_registration_sid?: string | null
      /** @description The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) that the resource is associated with. */
      messaging_service_sid?: string | null
      /** @description A short description of what this SMS campaign does. Min length: 40 characters. Max length: 4096 characters. */
      description?: string | null
      /** @description An array of sample message strings, min two and max five. Min length for each sample: 20 chars. Max length for each sample: 1024 chars. */
      message_samples?: string[] | null
      /** @description A2P Campaign Use Case. Examples: [ 2FA, EMERGENCY, MARKETING, SOLE_PROPRIETOR...]. SOLE_PROPRIETOR campaign use cases can only be created by SOLE_PROPRIETOR Brands, and there can only be one SOLE_PROPRIETOR campaign created per SOLE_PROPRIETOR Brand. */
      us_app_to_person_usecase?: string | null
      /** @description Indicate that this SMS campaign will send messages that contain links. */
      has_embedded_links?: boolean | null
      /** @description Indicates that this SMS campaign will send messages that contain phone numbers. */
      has_embedded_phone?: boolean | null
      /** @description Campaign status. Examples: IN_PROGRESS, VERIFIED, FAILED. */
      campaign_status?: string | null
      /** @description The Campaign Registry (TCR) Campaign ID. */
      campaign_id?: string | null
      /** @description Indicates whether the campaign was registered externally or not. */
      is_externally_registered?: boolean | null
      /** @description Rate limit and/or classification set by each carrier, Ex. AT&T or T-Mobile. */
      rate_limits?: unknown
      /** @description Details around how a consumer opts-in to their campaign, therefore giving consent to receive their messages. If multiple opt-in methods can be used for the same campaign, they must all be listed. 40 character minimum. 2048 character maximum. */
      message_flow?: string | null
      /** @description If end users can text in a keyword to start receiving messages from this campaign, the auto-reply messages sent to the end users must be provided. The opt-in response should include the Brand name, confirmation of opt-in enrollment to a recurring message campaign, how to get help, and clear description of how to opt-out. This field is required if end users can text in a keyword to start receiving messages from this campaign. 20 character minimum. 320 character maximum. */
      opt_in_message?: string | null
      /** @description Upon receiving the opt-out keywords from the end users, Twilio customers are expected to send back an auto-generated response, which must provide acknowledgment of the opt-out request and confirmation that no further messages will be sent. It is also recommended that these opt-out messages include the brand name. This field is required if managing opt out keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). 20 character minimum. 320 character maximum. */
      opt_out_message?: string | null
      /** @description When customers receive the help keywords from their end users, Twilio customers are expected to send back an auto-generated response; this may include the brand name and additional support contact information. This field is required if managing help keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). 20 character minimum. 320 character maximum. */
      help_message?: string | null
      /** @description If end users can text in a keyword to start receiving messages from this campaign, those keywords must be provided. This field is required if end users can text in a keyword to start receiving messages from this campaign. Values must be alphanumeric. 255 character maximum. */
      opt_in_keywords?: string[] | null
      /** @description End users should be able to text in a keyword to stop receiving messages from this campaign. Those keywords must be provided. This field is required if managing opt out keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). Values must be alphanumeric. 255 character maximum. */
      opt_out_keywords?: string[] | null
      /** @description End users should be able to text in a keyword to receive help. Those keywords must be provided as part of the campaign registration request. This field is required if managing help keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). Values must be alphanumeric. 255 character maximum. */
      help_keywords?: string[] | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_created?: string | null
      /**
       * Format: date-time
       * @description The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
       */
      date_updated?: string | null
      /**
       * Format: uri
       * @description The absolute URL of the US App to Person resource.
       */
      url?: string | null
      /** @description A boolean that specifies whether campaign is a mock or not. Mock campaigns will be automatically created if using a mock brand. Mock campaigns should only be used for testing purposes. */
      mock?: boolean | null
      /** @description Details indicating why a campaign registration failed. These errors can indicate one or more fields that were incorrect or did not meet review requirements. */
      errors?: unknown[] | null
    }
    'messaging.v1.service.us_app_to_person_usecase': {
      /** @description Human readable name, code, description and post_approval_required (indicates whether or not post approval is required for this Use Case) of A2P Campaign Use Cases. */
      us_app_to_person_usecases?: unknown[] | null
    }
    'messaging.v1.usecase': {
      /** @description Human readable use case details (usecase, description and purpose) of Messaging Service Use Cases. */
      usecases?: unknown[] | null
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  ListAlphaSender: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number
        /** @description The page index. This value is simply for client state. */
        Page?: number
        /** @description The page token. This is provided by the API. */
        PageToken?: string
      }
      path: {
        /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to read the resources from. */
        ServiceSid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            alpha_senders?: components['schemas']['messaging.v1.service.alpha_sender'][]
            meta?: {
              /** Format: uri */
              first_page_url?: string
              /** Format: uri */
              next_page_url?: string | null
              page?: number
              page_size?: number
              /** Format: uri */
              previous_page_url?: string | null
              /** Format: uri */
              url?: string
              key?: string
            }
          }
        }
      }
    }
  }
  CreateAlphaSender: {
    parameters: {
      path: {
        /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to create the resource under. */
        ServiceSid: string
      }
    }
    requestBody?: {
      content: {
        'application/x-www-form-urlencoded': {
          /** @description The Alphanumeric Sender ID string. Can be up to 11 characters long. Valid characters are A-Z, a-z, 0-9, space, hyphen `-`, plus `+`, underscore `_` and ampersand `&`. This value cannot contain only numbers. */
          AlphaSender: string
        }
      }
    }
    responses: {
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['messaging.v1.service.alpha_sender']
        }
      }
    }
  }
  FetchAlphaSender: {
    parameters: {
      path: {
        /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to fetch the resource from. */
        ServiceSid: string
        /** @description The SID of the AlphaSender resource to fetch. */
        Sid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.service.alpha_sender']
        }
      }
    }
  }
  DeleteAlphaSender: {
    parameters: {
      path: {
        /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to delete the resource from. */
        ServiceSid: string
        /** @description The SID of the AlphaSender resource to delete. */
        Sid: string
      }
    }
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never
      }
    }
  }
  CreateBrandRegistrationOtp: {
    parameters: {
      path: {
        /** @description Brand Registration Sid of Sole Proprietor Brand. */
        BrandRegistrationSid: string
      }
    }
    responses: {
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['messaging.v1.brand_registrations.brand_registration_otp']
        }
      }
    }
  }
  FetchBrandRegistrations: {
    parameters: {
      path: {
        /** @description The SID of the Brand Registration resource to fetch. */
        Sid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.brand_registrations']
        }
      }
    }
  }
  UpdateBrandRegistrations: {
    parameters: {
      path: {
        /** @description The SID of the Brand Registration resource to update. */
        Sid: string
      }
    }
    responses: {
      /** @description Accepted */
      202: {
        content: {
          'application/json': components['schemas']['messaging.v1.brand_registrations']
        }
      }
    }
  }
  ListBrandRegistrations: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number
        /** @description The page index. This value is simply for client state. */
        Page?: number
        /** @description The page token. This is provided by the API. */
        PageToken?: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            data?: components['schemas']['messaging.v1.brand_registrations'][]
            meta?: {
              /** Format: uri */
              first_page_url?: string
              /** Format: uri */
              next_page_url?: string | null
              page?: number
              page_size?: number
              /** Format: uri */
              previous_page_url?: string | null
              /** Format: uri */
              url?: string
              key?: string
            }
          }
        }
      }
    }
  }
  CreateBrandRegistrations: {
    requestBody?: {
      content: {
        'application/x-www-form-urlencoded': {
          /** @description Customer Profile Bundle Sid. */
          CustomerProfileBundleSid: string
          /** @description A2P Messaging Profile Bundle Sid. */
          A2PProfileBundleSid: string
          /** @description Type of brand being created. One of: "STANDARD", "SOLE_PROPRIETOR". SOLE_PROPRIETOR is for low volume, SOLE_PROPRIETOR use cases. STANDARD is for all other use cases. */
          BrandType?: string
          /** @description A boolean that specifies whether brand should be a mock or not. If true, brand will be registered as a mock brand. Defaults to false if no value is provided. */
          Mock?: boolean
          /** @description A flag to disable automatic secondary vetting for brands which it would otherwise be done. */
          SkipAutomaticSecVet?: boolean
        }
      }
    }
    responses: {
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['messaging.v1.brand_registrations']
        }
      }
    }
  }
  ListBrandVetting: {
    parameters: {
      query?: {
        /** @description The third-party provider of the vettings to read */
        VettingProvider?: components['schemas']['brand_vetting_enum_vetting_provider']
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number
        /** @description The page index. This value is simply for client state. */
        Page?: number
        /** @description The page token. This is provided by the API. */
        PageToken?: string
      }
      path: {
        /** @description The SID of the Brand Registration resource of the vettings to read . */
        BrandSid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            data?: components['schemas']['messaging.v1.brand_registrations.brand_vetting'][]
            meta?: {
              /** Format: uri */
              first_page_url?: string
              /** Format: uri */
              next_page_url?: string | null
              page?: number
              page_size?: number
              /** Format: uri */
              previous_page_url?: string | null
              /** Format: uri */
              url?: string
              key?: string
            }
          }
        }
      }
    }
  }
  CreateBrandVetting: {
    parameters: {
      path: {
        /** @description The SID of the Brand Registration resource of the vettings to create . */
        BrandSid: string
      }
    }
    requestBody?: {
      content: {
        'application/x-www-form-urlencoded': {
          /** @description The third-party provider of the vettings to create . */
          VettingProvider: components['schemas']['brand_vetting_enum_vetting_provider']
          /** @description The unique ID of the vetting */
          VettingId?: string
        }
      }
    }
    responses: {
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['messaging.v1.brand_registrations.brand_vetting']
        }
      }
    }
  }
  FetchBrandVetting: {
    parameters: {
      path: {
        /** @description The SID of the Brand Registration resource of the vettings to read . */
        BrandSid: string
        /** @description The Twilio SID of the third-party vetting record. */
        BrandVettingSid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.brand_registrations.brand_vetting']
        }
      }
    }
  }
  ListChannelSender: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number
        /** @description The page index. This value is simply for client state. */
        Page?: number
        /** @description The page token. This is provided by the API. */
        PageToken?: string
      }
      path: {
        /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to read the resources from. */
        MessagingServiceSid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            senders?: components['schemas']['messaging.v1.service.channel_sender'][]
            meta?: {
              /** Format: uri */
              first_page_url?: string
              /** Format: uri */
              next_page_url?: string | null
              page?: number
              page_size?: number
              /** Format: uri */
              previous_page_url?: string | null
              /** Format: uri */
              url?: string
              key?: string
            }
          }
        }
      }
    }
  }
  FetchChannelSender: {
    parameters: {
      path: {
        /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to fetch the resource from. */
        MessagingServiceSid: string
        /** @description The SID of the ChannelSender resource to fetch. */
        Sid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.service.channel_sender']
        }
      }
    }
  }
  /** @description Fetch a list of all United States numbers that have been deactivated on a specific date. */
  FetchDeactivation: {
    parameters: {
      query?: {
        /** @description The request will return a list of all United States Phone Numbers that were deactivated on the day specified by this parameter. This date should be specified in YYYY-MM-DD format. */
        Date?: string
      }
    }
    responses: {
      /** @description Temporary Redirect */
      307: {
        content: {
          'application/json': components['schemas']['messaging.v1.deactivation']
        }
      }
    }
  }
  FetchDomainCertV4: {
    parameters: {
      path: {
        /** @description Unique string used to identify the domain that this certificate should be associated with. */
        DomainSid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.domain_cert_v4']
        }
      }
    }
  }
  UpdateDomainCertV4: {
    parameters: {
      path: {
        /** @description Unique string used to identify the domain that this certificate should be associated with. */
        DomainSid: string
      }
    }
    requestBody?: {
      content: {
        'application/x-www-form-urlencoded': {
          /** @description Contains the full TLS certificate and private for this domain in PEM format: https://en.wikipedia.org/wiki/Privacy-Enhanced_Mail. Twilio uses this information to process HTTPS traffic sent to your domain. */
          TlsCert: string
        }
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.domain_cert_v4']
        }
      }
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['messaging.v1.domain_cert_v4']
        }
      }
    }
  }
  DeleteDomainCertV4: {
    parameters: {
      path: {
        /** @description Unique string used to identify the domain that this certificate should be associated with. */
        DomainSid: string
      }
    }
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never
      }
    }
  }
  FetchDomainConfig: {
    parameters: {
      path: {
        /** @description Unique string used to identify the domain that this config should be associated with. */
        DomainSid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.domain_config']
        }
      }
    }
  }
  UpdateDomainConfig: {
    parameters: {
      path: {
        /** @description Unique string used to identify the domain that this config should be associated with. */
        DomainSid: string
      }
    }
    requestBody?: {
      content: {
        'application/x-www-form-urlencoded': {
          /**
           * Format: uri
           * @description Any requests we receive to this domain that do not match an existing shortened message will be redirected to the fallback url. These will likely be either expired messages, random misdirected traffic, or intentional scraping.
           */
          FallbackUrl?: string
          /**
           * Format: uri
           * @description URL to receive click events to your webhook whenever the recipients click on the shortened links
           */
          CallbackUrl?: string
          /** @description Boolean field to set customer delivery preference when there is a failure in linkShortening service */
          ContinueOnFailure?: boolean
          /** @description Customer's choice to send links with/without "https://" attached to shortened url. If true, messages will not be sent with https:// at the beginning of the url. If false, messages will be sent with https:// at the beginning of the url. False is the default behavior if it is not specified. */
          DisableHttps?: boolean
        }
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.domain_config']
        }
      }
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['messaging.v1.domain_config']
        }
      }
    }
  }
  FetchDomainConfigMessagingService: {
    parameters: {
      path: {
        /** @description Unique string used to identify the Messaging service that this domain should be associated with. */
        MessagingServiceSid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.domain_config_messaging_service']
        }
      }
    }
  }
  CreateExternalCampaign: {
    requestBody?: {
      content: {
        'application/x-www-form-urlencoded': {
          /** @description ID of the preregistered campaign. */
          CampaignId: string
          /** @description The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) that the resource is associated with. */
          MessagingServiceSid: string
        }
      }
    }
    responses: {
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['messaging.v1.external_campaign']
        }
      }
    }
  }
  CreateLinkshorteningMessagingService: {
    parameters: {
      path: {
        /** @description The domain SID to associate with a messaging service. With URL shortening enabled, links in messages sent with the associated messaging service will be shortened to the provided domain */
        DomainSid: string
        /** @description A messaging service SID to associate with a domain. With URL shortening enabled, links in messages sent with the provided messaging service will be shortened to the associated domain */
        MessagingServiceSid: string
      }
    }
    responses: {
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['messaging.v1.linkshortening_messaging_service']
        }
      }
    }
  }
  DeleteLinkshorteningMessagingService: {
    parameters: {
      path: {
        /** @description The domain SID to dissociate from a messaging service. With URL shortening enabled, links in messages sent with the associated messaging service will be shortened to the provided domain */
        DomainSid: string
        /** @description A messaging service SID to dissociate from a domain. With URL shortening enabled, links in messages sent with the provided messaging service will be shortened to the associated domain */
        MessagingServiceSid: string
      }
    }
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never
      }
    }
  }
  FetchLinkshorteningMessagingServiceDomainAssociation: {
    parameters: {
      path: {
        /** @description Unique string used to identify the Messaging service that this domain should be associated with. */
        MessagingServiceSid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.linkshortening_messaging_service_domain_association']
        }
      }
    }
  }
  ListPhoneNumber: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number
        /** @description The page index. This value is simply for client state. */
        Page?: number
        /** @description The page token. This is provided by the API. */
        PageToken?: string
      }
      path: {
        /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to read the resources from. */
        ServiceSid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            phone_numbers?: components['schemas']['messaging.v1.service.phone_number'][]
            meta?: {
              /** Format: uri */
              first_page_url?: string
              /** Format: uri */
              next_page_url?: string | null
              page?: number
              page_size?: number
              /** Format: uri */
              previous_page_url?: string | null
              /** Format: uri */
              url?: string
              key?: string
            }
          }
        }
      }
    }
  }
  CreatePhoneNumber: {
    parameters: {
      path: {
        /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to create the resource under. */
        ServiceSid: string
      }
    }
    requestBody?: {
      content: {
        'application/x-www-form-urlencoded': {
          /** @description The SID of the Phone Number being added to the Service. */
          PhoneNumberSid: string
        }
      }
    }
    responses: {
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['messaging.v1.service.phone_number']
        }
      }
    }
  }
  FetchPhoneNumber: {
    parameters: {
      path: {
        /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to fetch the resource from. */
        ServiceSid: string
        /** @description The SID of the PhoneNumber resource to fetch. */
        Sid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.service.phone_number']
        }
      }
    }
  }
  DeletePhoneNumber: {
    parameters: {
      path: {
        /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to delete the resource from. */
        ServiceSid: string
        /** @description The SID of the PhoneNumber resource to delete. */
        Sid: string
      }
    }
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never
      }
    }
  }
  ListService: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number
        /** @description The page index. This value is simply for client state. */
        Page?: number
        /** @description The page token. This is provided by the API. */
        PageToken?: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            services?: components['schemas']['messaging.v1.service'][]
            meta?: {
              /** Format: uri */
              first_page_url?: string
              /** Format: uri */
              next_page_url?: string | null
              page?: number
              page_size?: number
              /** Format: uri */
              previous_page_url?: string | null
              /** Format: uri */
              url?: string
              key?: string
            }
          }
        }
      }
    }
  }
  CreateService: {
    requestBody?: {
      content: {
        'application/x-www-form-urlencoded': {
          /** @description A descriptive string that you create to describe the resource. It can be up to 64 characters long. */
          FriendlyName: string
          /**
           * Format: uri
           * @description The URL we call using `inbound_method` when a message is received by any phone number or short code in the Service. When this property is `null`, receiving inbound messages is disabled. All messages sent to the Twilio phone number or short code will not be logged and received on the Account. If the `use_inbound_webhook_on_number` field is enabled then the webhook url defined on the phone number will override the `inbound_request_url` defined for the Messaging Service.
           */
          InboundRequestUrl?: string
          /**
           * Format: http-method
           * @description The HTTP method we should use to call `inbound_request_url`. Can be `GET` or `POST` and the default is `POST`.
           * @enum {string}
           */
          InboundMethod?: 'HEAD' | 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE'
          /**
           * Format: uri
           * @description The URL that we call using `fallback_method` if an error occurs while retrieving or executing the TwiML from the Inbound Request URL. If the `use_inbound_webhook_on_number` field is enabled then the webhook url defined on the phone number will override the `fallback_url` defined for the Messaging Service.
           */
          FallbackUrl?: string
          /**
           * Format: http-method
           * @description The HTTP method we should use to call `fallback_url`. Can be: `GET` or `POST`.
           * @enum {string}
           */
          FallbackMethod?: 'HEAD' | 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE'
          /**
           * Format: uri
           * @description The URL we should call to [pass status updates](https://www.twilio.com/docs/sms/api/message-resource#message-status-values) about message delivery.
           */
          StatusCallback?: string
          /** @description Whether to enable [Sticky Sender](https://www.twilio.com/docs/messaging/services#sticky-sender) on the Service instance. */
          StickySender?: boolean
          /** @description Whether to enable the [MMS Converter](https://www.twilio.com/docs/messaging/services#mms-converter) for messages sent through the Service instance. */
          MmsConverter?: boolean
          /** @description Whether to enable [Smart Encoding](https://www.twilio.com/docs/messaging/services#smart-encoding) for messages sent through the Service instance. */
          SmartEncoding?: boolean
          /** @description Reserved. */
          ScanMessageContent?: components['schemas']['service_enum_scan_message_content']
          /** @description [OBSOLETE] Former feature used to fallback to long code sender after certain short code message failures. */
          FallbackToLongCode?: boolean
          /** @description Whether to enable [Area Code Geomatch](https://www.twilio.com/docs/messaging/services#area-code-geomatch) on the Service Instance. */
          AreaCodeGeomatch?: boolean
          /** @description How long, in seconds, messages sent from the Service are valid. Can be an integer from `1` to `14,400`. */
          ValidityPeriod?: number
          /** @description Reserved. */
          SynchronousValidation?: boolean
          /** @description A string that describes the scenario in which the Messaging Service will be used. Possible values are `notifications`, `marketing`, `verification`, `discussion`, `poll`, `undeclared`. */
          Usecase?: string
          /** @description A boolean value that indicates either the webhook url configured on the phone number will be used or `inbound_request_url`/`fallback_url` url will be called when a message is received from the phone number. If this field is enabled then the webhook url defined on the phone number will override the `inbound_request_url`/`fallback_url` defined for the Messaging Service. */
          UseInboundWebhookOnNumber?: boolean
        }
      }
    }
    responses: {
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['messaging.v1.service']
        }
      }
    }
  }
  FetchService: {
    parameters: {
      path: {
        /** @description The SID of the Service resource to fetch. */
        Sid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.service']
        }
      }
    }
  }
  UpdateService: {
    parameters: {
      path: {
        /** @description The SID of the Service resource to update. */
        Sid: string
      }
    }
    requestBody?: {
      content: {
        'application/x-www-form-urlencoded': {
          /** @description A descriptive string that you create to describe the resource. It can be up to 64 characters long. */
          FriendlyName?: string
          /**
           * Format: uri
           * @description The URL we call using `inbound_method` when a message is received by any phone number or short code in the Service. When this property is `null`, receiving inbound messages is disabled. All messages sent to the Twilio phone number or short code will not be logged and received on the Account. If the `use_inbound_webhook_on_number` field is enabled then the webhook url defined on the phone number will override the `inbound_request_url` defined for the Messaging Service.
           */
          InboundRequestUrl?: string
          /**
           * Format: http-method
           * @description The HTTP method we should use to call `inbound_request_url`. Can be `GET` or `POST` and the default is `POST`.
           * @enum {string}
           */
          InboundMethod?: 'HEAD' | 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE'
          /**
           * Format: uri
           * @description The URL that we call using `fallback_method` if an error occurs while retrieving or executing the TwiML from the Inbound Request URL. If the `use_inbound_webhook_on_number` field is enabled then the webhook url defined on the phone number will override the `fallback_url` defined for the Messaging Service.
           */
          FallbackUrl?: string
          /**
           * Format: http-method
           * @description The HTTP method we should use to call `fallback_url`. Can be: `GET` or `POST`.
           * @enum {string}
           */
          FallbackMethod?: 'HEAD' | 'GET' | 'POST' | 'PATCH' | 'PUT' | 'DELETE'
          /**
           * Format: uri
           * @description The URL we should call to [pass status updates](https://www.twilio.com/docs/sms/api/message-resource#message-status-values) about message delivery.
           */
          StatusCallback?: string
          /** @description Whether to enable [Sticky Sender](https://www.twilio.com/docs/messaging/services#sticky-sender) on the Service instance. */
          StickySender?: boolean
          /** @description Whether to enable the [MMS Converter](https://www.twilio.com/docs/messaging/services#mms-converter) for messages sent through the Service instance. */
          MmsConverter?: boolean
          /** @description Whether to enable [Smart Encoding](https://www.twilio.com/docs/messaging/services#smart-encoding) for messages sent through the Service instance. */
          SmartEncoding?: boolean
          /** @description Reserved. */
          ScanMessageContent?: components['schemas']['service_enum_scan_message_content']
          /** @description [OBSOLETE] Former feature used to fallback to long code sender after certain short code message failures. */
          FallbackToLongCode?: boolean
          /** @description Whether to enable [Area Code Geomatch](https://www.twilio.com/docs/messaging/services#area-code-geomatch) on the Service Instance. */
          AreaCodeGeomatch?: boolean
          /** @description How long, in seconds, messages sent from the Service are valid. Can be an integer from `1` to `14,400`. */
          ValidityPeriod?: number
          /** @description Reserved. */
          SynchronousValidation?: boolean
          /** @description A string that describes the scenario in which the Messaging Service will be used. Possible values are `notifications`, `marketing`, `verification`, `discussion`, `poll`, `undeclared`. */
          Usecase?: string
          /** @description A boolean value that indicates either the webhook url configured on the phone number will be used or `inbound_request_url`/`fallback_url` url will be called when a message is received from the phone number. If this field is enabled then the webhook url defined on the phone number will override the `inbound_request_url`/`fallback_url` defined for the Messaging Service. */
          UseInboundWebhookOnNumber?: boolean
        }
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.service']
        }
      }
    }
  }
  DeleteService: {
    parameters: {
      path: {
        /** @description The SID of the Service resource to delete. */
        Sid: string
      }
    }
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never
      }
    }
  }
  ListShortCode: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number
        /** @description The page index. This value is simply for client state. */
        Page?: number
        /** @description The page token. This is provided by the API. */
        PageToken?: string
      }
      path: {
        /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to read the resources from. */
        ServiceSid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            short_codes?: components['schemas']['messaging.v1.service.short_code'][]
            meta?: {
              /** Format: uri */
              first_page_url?: string
              /** Format: uri */
              next_page_url?: string | null
              page?: number
              page_size?: number
              /** Format: uri */
              previous_page_url?: string | null
              /** Format: uri */
              url?: string
              key?: string
            }
          }
        }
      }
    }
  }
  CreateShortCode: {
    parameters: {
      path: {
        /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to create the resource under. */
        ServiceSid: string
      }
    }
    requestBody?: {
      content: {
        'application/x-www-form-urlencoded': {
          /** @description The SID of the ShortCode resource being added to the Service. */
          ShortCodeSid: string
        }
      }
    }
    responses: {
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['messaging.v1.service.short_code']
        }
      }
    }
  }
  FetchShortCode: {
    parameters: {
      path: {
        /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to fetch the resource from. */
        ServiceSid: string
        /** @description The SID of the ShortCode resource to fetch. */
        Sid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.service.short_code']
        }
      }
    }
  }
  DeleteShortCode: {
    parameters: {
      path: {
        /** @description The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) to delete the resource from. */
        ServiceSid: string
        /** @description The SID of the ShortCode resource to delete. */
        Sid: string
      }
    }
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never
      }
    }
  }
  FetchTollfreeVerification: {
    parameters: {
      path: {
        /** @description The unique string to identify Tollfree Verification. */
        Sid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.tollfree_verification']
        }
      }
    }
  }
  UpdateTollfreeVerification: {
    parameters: {
      path: {
        /** @description The unique string to identify Tollfree Verification. */
        Sid: string
      }
    }
    requestBody?: {
      content: {
        'application/x-www-form-urlencoded': {
          /** @description The name of the business or organization using the Tollfree number. */
          BusinessName?: string
          /** @description The website of the business or organization using the Tollfree number. */
          BusinessWebsite?: string
          /** @description The email address to receive the notification about the verification result. . */
          NotificationEmail?: string
          /** @description The category of the use case for the Tollfree Number. List as many are applicable.. */
          UseCaseCategories?: string[]
          /** @description Use this to further explain how messaging is used by the business or organization. */
          UseCaseSummary?: string
          /** @description An example of message content, i.e. a sample message. */
          ProductionMessageSample?: string
          /** @description Link to an image that shows the opt-in workflow. Multiple images allowed and must be a publicly hosted URL. */
          OptInImageUrls?: string[]
          /** @description Describe how a user opts-in to text messages. */
          OptInType?: components['schemas']['tollfree_verification_enum_opt_in_type']
          /** @description Estimate monthly volume of messages from the Tollfree Number. */
          MessageVolume?: string
          /** @description The address of the business or organization using the Tollfree number. */
          BusinessStreetAddress?: string
          /** @description The address of the business or organization using the Tollfree number. */
          BusinessStreetAddress2?: string
          /** @description The city of the business or organization using the Tollfree number. */
          BusinessCity?: string
          /** @description The state/province/region of the business or organization using the Tollfree number. */
          BusinessStateProvinceRegion?: string
          /** @description The postal code of the business or organization using the Tollfree number. */
          BusinessPostalCode?: string
          /** @description The country of the business or organization using the Tollfree number. */
          BusinessCountry?: string
          /** @description Additional information to be provided for verification. */
          AdditionalInformation?: string
          /** @description The first name of the contact for the business or organization using the Tollfree number. */
          BusinessContactFirstName?: string
          /** @description The last name of the contact for the business or organization using the Tollfree number. */
          BusinessContactLastName?: string
          /** @description The email address of the contact for the business or organization using the Tollfree number. */
          BusinessContactEmail?: string
          /**
           * Format: phone-number
           * @description The phone number of the contact for the business or organization using the Tollfree number.
           */
          BusinessContactPhone?: string
          /** @description Describe why the verification is being edited. If the verification was rejected because of a technical issue, such as the website being down, and the issue has been resolved this parameter should be set to something similar to 'Website fixed'. */
          EditReason?: string
        }
      }
    }
    responses: {
      /** @description Accepted */
      202: {
        content: {
          'application/json': components['schemas']['messaging.v1.tollfree_verification']
        }
      }
    }
  }
  DeleteTollfreeVerification: {
    parameters: {
      path: {
        /** @description The unique string to identify Tollfree Verification. */
        Sid: string
      }
    }
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never
      }
    }
  }
  ListTollfreeVerification: {
    parameters: {
      query?: {
        /** @description The SID of the Phone Number associated with the Tollfree Verification. */
        TollfreePhoneNumberSid?: string
        /** @description The compliance status of the Tollfree Verification record. */
        Status?: components['schemas']['tollfree_verification_enum_status']
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number
        /** @description The page index. This value is simply for client state. */
        Page?: number
        /** @description The page token. This is provided by the API. */
        PageToken?: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            verifications?: components['schemas']['messaging.v1.tollfree_verification'][]
            meta?: {
              /** Format: uri */
              first_page_url?: string
              /** Format: uri */
              next_page_url?: string | null
              page?: number
              page_size?: number
              /** Format: uri */
              previous_page_url?: string | null
              /** Format: uri */
              url?: string
              key?: string
            }
          }
        }
      }
    }
  }
  CreateTollfreeVerification: {
    requestBody?: {
      content: {
        'application/x-www-form-urlencoded': {
          /** @description The name of the business or organization using the Tollfree number. */
          BusinessName: string
          /** @description The website of the business or organization using the Tollfree number. */
          BusinessWebsite: string
          /** @description The email address to receive the notification about the verification result. . */
          NotificationEmail: string
          /** @description The category of the use case for the Tollfree Number. List as many are applicable.. */
          UseCaseCategories: string[]
          /** @description Use this to further explain how messaging is used by the business or organization. */
          UseCaseSummary: string
          /** @description An example of message content, i.e. a sample message. */
          ProductionMessageSample: string
          /** @description Link to an image that shows the opt-in workflow. Multiple images allowed and must be a publicly hosted URL. */
          OptInImageUrls: string[]
          /** @description Describe how a user opts-in to text messages. */
          OptInType: components['schemas']['tollfree_verification_enum_opt_in_type']
          /** @description Estimate monthly volume of messages from the Tollfree Number. */
          MessageVolume: string
          /** @description The SID of the Phone Number associated with the Tollfree Verification. */
          TollfreePhoneNumberSid: string
          /** @description Customer's Profile Bundle BundleSid. */
          CustomerProfileSid?: string
          /** @description The address of the business or organization using the Tollfree number. */
          BusinessStreetAddress?: string
          /** @description The address of the business or organization using the Tollfree number. */
          BusinessStreetAddress2?: string
          /** @description The city of the business or organization using the Tollfree number. */
          BusinessCity?: string
          /** @description The state/province/region of the business or organization using the Tollfree number. */
          BusinessStateProvinceRegion?: string
          /** @description The postal code of the business or organization using the Tollfree number. */
          BusinessPostalCode?: string
          /** @description The country of the business or organization using the Tollfree number. */
          BusinessCountry?: string
          /** @description Additional information to be provided for verification. */
          AdditionalInformation?: string
          /** @description The first name of the contact for the business or organization using the Tollfree number. */
          BusinessContactFirstName?: string
          /** @description The last name of the contact for the business or organization using the Tollfree number. */
          BusinessContactLastName?: string
          /** @description The email address of the contact for the business or organization using the Tollfree number. */
          BusinessContactEmail?: string
          /**
           * Format: phone-number
           * @description The phone number of the contact for the business or organization using the Tollfree number.
           */
          BusinessContactPhone?: string
          /** @description An optional external reference ID supplied by customer and echoed back on status retrieval. */
          ExternalReferenceId?: string
        }
      }
    }
    responses: {
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['messaging.v1.tollfree_verification']
        }
      }
    }
  }
  ListUsAppToPerson: {
    parameters: {
      query?: {
        /** @description How many resources to return in each list page. The default is 50, and the maximum is 1000. */
        PageSize?: number
        /** @description The page index. This value is simply for client state. */
        Page?: number
        /** @description The page token. This is provided by the API. */
        PageToken?: string
      }
      path: {
        /** @description The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) to fetch the resource from. */
        MessagingServiceSid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': {
            compliance?: components['schemas']['messaging.v1.service.us_app_to_person'][]
            meta?: {
              /** Format: uri */
              first_page_url?: string
              /** Format: uri */
              next_page_url?: string | null
              page?: number
              page_size?: number
              /** Format: uri */
              previous_page_url?: string | null
              /** Format: uri */
              url?: string
              key?: string
            }
          }
        }
      }
    }
  }
  CreateUsAppToPerson: {
    parameters: {
      path: {
        /** @description The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) to create the resources from. */
        MessagingServiceSid: string
      }
    }
    requestBody?: {
      content: {
        'application/x-www-form-urlencoded': {
          /** @description A2P Brand Registration SID */
          BrandRegistrationSid: string
          /** @description A short description of what this SMS campaign does. Min length: 40 characters. Max length: 4096 characters. */
          Description: string
          /** @description Required for all Campaigns. Details around how a consumer opts-in to their campaign, therefore giving consent to receive their messages. If multiple opt-in methods can be used for the same campaign, they must all be listed. 40 character minimum. 2048 character maximum. */
          MessageFlow: string
          /** @description An array of sample message strings, min two and max five. Min length for each sample: 20 chars. Max length for each sample: 1024 chars. */
          MessageSamples: string[]
          /** @description A2P Campaign Use Case. Examples: [ 2FA, EMERGENCY, MARKETING..] */
          UsAppToPersonUsecase: string
          /** @description Indicates that this SMS campaign will send messages that contain links. */
          HasEmbeddedLinks: boolean
          /** @description Indicates that this SMS campaign will send messages that contain phone numbers. */
          HasEmbeddedPhone: boolean
          /** @description If end users can text in a keyword to start receiving messages from this campaign, the auto-reply messages sent to the end users must be provided. The opt-in response should include the Brand name, confirmation of opt-in enrollment to a recurring message campaign, how to get help, and clear description of how to opt-out. This field is required if end users can text in a keyword to start receiving messages from this campaign. 20 character minimum. 320 character maximum. */
          OptInMessage?: string
          /** @description Upon receiving the opt-out keywords from the end users, Twilio customers are expected to send back an auto-generated response, which must provide acknowledgment of the opt-out request and confirmation that no further messages will be sent. It is also recommended that these opt-out messages include the brand name. This field is required if managing opt out keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). 20 character minimum. 320 character maximum. */
          OptOutMessage?: string
          /** @description When customers receive the help keywords from their end users, Twilio customers are expected to send back an auto-generated response; this may include the brand name and additional support contact information. This field is required if managing help keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). 20 character minimum. 320 character maximum. */
          HelpMessage?: string
          /** @description If end users can text in a keyword to start receiving messages from this campaign, those keywords must be provided. This field is required if end users can text in a keyword to start receiving messages from this campaign. Values must be alphanumeric. 255 character maximum. */
          OptInKeywords?: string[]
          /** @description End users should be able to text in a keyword to stop receiving messages from this campaign. Those keywords must be provided. This field is required if managing opt out keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). Values must be alphanumeric. 255 character maximum. */
          OptOutKeywords?: string[]
          /** @description End users should be able to text in a keyword to receive help. Those keywords must be provided as part of the campaign registration request. This field is required if managing help keywords yourself (i.e. not using Twilio's Default or Advanced Opt Out features). Values must be alphanumeric. 255 character maximum. */
          HelpKeywords?: string[]
        }
      }
    }
    responses: {
      /** @description Created */
      201: {
        content: {
          'application/json': components['schemas']['messaging.v1.service.us_app_to_person']
        }
      }
    }
  }
  FetchUsAppToPerson: {
    parameters: {
      path: {
        /** @description The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) to fetch the resource from. */
        MessagingServiceSid: string
        /** @description The SID of the US A2P Compliance resource to fetch `QE2c6890da8086d771620e9b13fadeba0b`. */
        Sid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.service.us_app_to_person']
        }
      }
    }
  }
  DeleteUsAppToPerson: {
    parameters: {
      path: {
        /** @description The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) to delete the resource from. */
        MessagingServiceSid: string
        /** @description The SID of the US A2P Compliance resource to delete `QE2c6890da8086d771620e9b13fadeba0b`. */
        Sid: string
      }
    }
    responses: {
      /** @description The resource was deleted successfully. */
      204: {
        content: never
      }
    }
  }
  FetchUsAppToPersonUsecase: {
    parameters: {
      query?: {
        /** @description The unique string to identify the A2P brand. */
        BrandRegistrationSid?: string
      }
      path: {
        /** @description The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) to fetch the resource from. */
        MessagingServiceSid: string
      }
    }
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.service.us_app_to_person_usecase']
        }
      }
    }
  }
  FetchUsecase: {
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['messaging.v1.usecase']
        }
      }
    }
  }
}

export interface oasTypes {
  components: components
  external: external
  operations: operations
  paths: paths
  webhooks: webhooks
}

export default oasTypes
