// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {title: 'Merge API', version: '0.0.0'},
  servers: [{url: 'https://api.merge.dev/api'}],
} as const
export default oasMeta
