// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    title: 'Merge Accounting API',
    version: '1.0',
    description:
      'The unified API for building rich integrations with multiple Accounting & Finance platforms.',
    contact: {
      name: 'Merge Team',
      url: 'https://www.merge.dev/',
      email: 'hello@merge.dev',
    },
  },
  servers: [
    {url: 'https://api.merge.dev/api/accounting/v1', description: 'Production'},
    {
      url: 'https://api-sandbox.merge.dev/api/accounting/v1',
      description: 'Sandbox',
    },
    {
      url: 'https://api-eu.merge.dev/api/accounting/v1',
      description: 'Production EU',
    },
  ],
} as const
export default oasMeta
