// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    version: '0.25.6',
    title: 'Actions API',
    contact: {
      name: 'Supaglue',
      email: 'docs@supaglue.com',
      url: 'https://supaglue.com',
    },
    description:
      '#### Introduction\n\nWelcome to the Actions API documentation. Actions are helpful APIs scoped to Providers. They range from handling CRUD operations on objects to performing multi-step workflows.\n\n[![Run in Postman](https://run.pstmn.io/button.svg)](https://www.postman.com/supaglue/workspace/supaglue-public/overview)\n\n#### Base API URL\n```\nhttps://api.supaglue.io/actions/v2\n```\n',
  },
  servers: [
    {url: 'https://api.supaglue.io/actions/v2', description: 'Supaglue API'},
  ],
} as const
export default oasMeta
