// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    version: '0.25.6',
    title: 'Management API',
    contact: {
      name: 'Supaglue',
      email: 'docs@supaglue.com',
      url: 'https://supaglue.com',
    },
    description:
      '#### Introduction\n\nWelcome to the Management API documentation. You can use this API to manage customer integrations and connections.\n\n#### Base API URL\n\n```\nhttps://api.supaglue.io/mgmt/v2\n```\n',
  },
  servers: [
    {url: 'https://api.supaglue.io/mgmt/v2', description: 'Supaglue API'},
  ],
} as const
export default oasMeta
