// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    version: '0.13.13',
    title: 'Data Listing API',
    contact: {
      name: 'Supaglue',
      email: 'docs@supaglue.com',
      url: 'https://supaglue.com',
    },
    description:
      '#### Introduction\n\nWelcome to the Provider API documentation for Data Listing. You can use this API to list standard and custom objects to sync them from Supaglue to your database.\n\n:::info\n**NOTE**: To use the Data Listing API you need to use the Supaglue Managed Destination and select [Standard Objects](https://docs.supaglue.com/next/platform/objects/overview#configuration) to be synced.\n:::\n\n[![Run in Postman](https://run.pstmn.io/button.svg)](https://www.postman.com/supaglue/workspace/supaglue-public/overview)\n\n#### Base API URL\n```\nhttps://api.supaglue.io/data/v2\n```\n',
  },
  servers: [
    {url: 'https://api.supaglue.io/data/v2', description: 'Supaglue API'},
  ],
} as const
export default oasMeta
