/**
 * This file was generated by @opensdks/cli, do not edit manually.
 * For bugs & feature requests, please open an issue on the [GitHub](https://github.com/tonyxiao/openSDKs)
 */

import type {ClientOptions, SdkDefinition, SDKTypes} from '@opensdks/runtime'
import {initSDK} from '@opensdks/runtime'
import type {oasTypes} from '../clerk.oas.types.js'
import {oasMeta} from './clerk.oas.meta.js'

export type ClerkSDKTypes = SDKTypes<oasTypes, ClientOptions>

export const clerkSdkDef = {
  types: {} as ClerkSDKTypes,
  oasMeta,
} satisfies SdkDefinition<ClerkSDKTypes>

export function initClerkSDK(opts: ClerkSDKTypes['options']) {
  return initSDK(clerkSdkDef, opts)
}

export type ClerkSDK = ReturnType<typeof initClerkSDK>

export default initClerkSDK
