// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {title: 'Chargepoint', version: '0.0.0'},
  servers: [
    {url: 'https://sso.chargepoint.com/api/v1', description: 'SSO'},
    {url: 'https://na.chargepoint.com', description: 'NA'},
  ],
} as const
export default oasMeta
