// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {title: 'Notion API', version: '1'},
  servers: [{url: 'https://api.notion.com'}],
} as const
export default oasMeta
