// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    title: 'Discord HTTP API (Preview)',
    description:
      'Preview of the Discord v10 HTTP API specification. See https://discord.com/developers/docs for more details.',
    termsOfService:
      'https://discord.com/developers/docs/policies-and-agreements/developer-terms-of-service',
    license: {name: 'MIT', identifier: 'MIT'},
    version: '10',
  },
  servers: [{url: 'https://discord.com/api/v10'}],
} as const
export default oasMeta
