// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    title: 'Contacts',
    description: '',
    version: 'v3',
    'x-hubspot-product-tier-requirements': {
      marketing: 'FREE',
      sales: 'FREE',
      service: 'FREE',
      cms: 'FREE',
    },
    'x-hubspot-documentation-banner': 'NONE',
    'x-hubspot-api-use-case':
      'Retrieve a contact list by ID to bring that contact data into your external system.',
    'x-hubspot-related-documentation': [
      {
        name: 'Contacts Guide',
        url: 'https://hubspot.dev/guides/api/crm/contacts',
      },
    ],
    'x-hubspot-introduction':
      'Use the contact lists API to create and manage contact lists.',
  },
  servers: [{url: 'https://api.hubapi.com'}],
} as const
export default oasMeta
