// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    title: 'Authors',
    description:
      'Use these endpoints for interacting with Blog Posts, Blog Authors, and Blog Tags',
    version: 'v3',
    'x-hubspot-product-tier-requirements': {
      marketing: 'PROFESSIONAL',
      cms: 'STARTER',
    },
    'x-hubspot-documentation-banner': 'NONE',
    'x-hubspot-api-use-case':
      'After hiring a new blog writer, you need to create a new blog author profile for them so that readers can learn more about the author on each of their posts.',
    'x-hubspot-related-documentation': [
      {
        name: 'Blog Authors Guide',
        url: 'https://hubspot.dev/guides/api/cms/blog-authors',
      },
    ],
    'x-hubspot-introduction':
      'Use the blog authors API to manage information about blog post authors.',
  },
  servers: [{url: 'https://api.hubapi.com'}],
} as const
export default oasMeta
