// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    title: 'Feedback Submissions',
    description: '',
    version: 'v3',
    'x-hubspot-product-tier-requirements': {
      marketing: 'FREE',
      sales: 'FREE',
      service: 'FREE',
      cms: 'FREE',
    },
    'x-hubspot-documentation-banner': 'NONE',
    'x-hubspot-api-use-case':
      'To prepare for an upcoming product redesign, programmatically retrieve all feedback survey responses to better understand customer sentiment.',
    'x-hubspot-related-documentation': [
      {
        name: 'Feedback Submissions Guide',
        url: 'https://hubspot.dev/guides/api/crm/feedback-submissions',
      },
    ],
    'x-hubspot-introduction':
      'Use the feedback submissions API to retrieve information submitted to your NPS, CSAT, CES, and custom feedback surveys.',
  },
  servers: [{url: 'https://api.hubapi.com'}],
} as const
export default oasMeta
