// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    title: 'CMS Domains',
    version: 'v3',
    'x-hubspot-product-tier-requirements': {
      marketing: 'PROFESSIONAL',
      cms: 'STARTER',
    },
    'x-hubspot-documentation-banner': 'NONE',
    'x-hubspot-api-use-case':
      'Retrieve all currently connected domains to see which sites are live in a given account.',
    'x-hubspot-related-documentation': [
      {
        name: 'Domains Guide',
        url: 'https://hubspot.dev/guides/api/cms/domains',
      },
    ],
    'x-hubspot-introduction':
      'Use the domain management API to return information about the domains connected to a HubSpot account. You can return data for all currently connected domains, or for a single domain by ID.',
  },
  servers: [{url: 'https://api.hubapi.com'}],
} as const
export default oasMeta
