// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    title: 'Tags',
    description:
      'Use these endpoints for interacting with Blog Posts, Blog Authors, and Blog Tags',
    version: 'v3',
    'x-hubspot-product-tier-requirements': {
      marketing: 'PROFESSIONAL',
      cms: 'STARTER',
    },
    'x-hubspot-documentation-banner': 'NONE',
    'x-hubspot-api-use-case':
      'Retrieve all blog tags as a part of a content audit, then update specific tags to support an upcoming company rebrand.',
    'x-hubspot-related-documentation': [
      {
        name: 'Blog Tags Guide',
        url: 'https://hubspot.dev/guides/api/cms/blog-tags',
      },
    ],
    'x-hubspot-introduction':
      'Use the blog tags API to create and manage available blog post tags for easy sorting and filtering on your site.',
  },
  servers: [{url: 'https://api.hubapi.com'}],
} as const
export default oasMeta
