// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    title: 'Associations',
    description:
      'Associations define the relationships between objects in HubSpot. These endpoints allow you to create, read, and remove associations.',
    version: 'v3',
  },
  servers: [{url: 'https://api.hubapi.com/crm/v3/associations'}],
} as const
export default oasMeta
