// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    title: 'CRM Timeline',
    description:
      "This feature allows an app to create and configure custom events that can show up in the timelines of certain CRM objects like contacts, companies, tickets, or deals. You'll find multiple use cases for this API in the sections below.",
    version: 'v3',
    'x-hubspot-product-tier-requirements': {
      marketing: 'FREE',
      sales: 'FREE',
      service: 'FREE',
      cms: 'STARTER',
    },
    'x-hubspot-documentation-banner': 'NONE',
    'x-hubspot-api-use-case':
      'After setting up a new set of sign-up flows on your website, update contact timelines to indicate which flow they completed. In each event, you could also include a link to open an iframe that displays additional external data about the event.',
    'x-hubspot-related-documentation': [
      {
        name: 'Timeline Events Guide',
        url: 'https://hubspot.dev/guides/api/crm/timeline',
      },
    ],
    'x-hubspot-introduction':
      "Use the timeline events API to add custom event information to CRM record timelines. You'll first need to create a public app, then an event template to display event data. ",
  },
  servers: [{url: 'https://api.hubapi.com'}],
} as const
export default oasMeta
