// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    title: 'Schemas',
    description:
      "The CRM uses schemas to define how custom objects should store and represent information in the HubSpot CRM. Schemas define details about an object's type, properties, and associations. The schema can be uniquely identified by its **object type ID**.",
    version: 'v3',
    'x-hubspot-product-tier-requirements': {
      marketing: 'FREE',
      sales: 'FREE',
      service: 'FREE',
      cms: 'FREE',
    },
    'x-hubspot-documentation-banner': 'NONE',
    'x-hubspot-api-use-case':
      'Create a new object for storing information about cars at a car dealership. Your object definition could include properties to store information as well as the filters available on the custom object index page.',
    'x-hubspot-related-documentation': [
      {
        name: 'Custom Object Guide',
        url: 'https://hubspot.dev/guides/api/crm/crm-custom-objects',
      },
    ],
    'x-hubspot-introduction':
      "Use the custom objects schema API to define new types of CRM records in your account. After setting up an object schema, you'll then be able to create custom records under that object both in HubSpot and using the custom object records API.",
  },
  servers: [{url: 'https://api.hubapi.com'}],
} as const
export default oasMeta
