/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/events/v3/events/': {
    get: operations['get-/events/v3/events/_getPage']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    ErrorDetail: {
      /** @description A specific category that contains more specific detail about the error */
      subCategory?: string
      /** @description The status code associated with the error detail */
      code?: string
      /** @description The name of the field or parameter in which the error was found. */
      in?: string
      /**
       * @description Context about the error condition
       * @example {
       *   "missingScopes": [
       *     "scope1",
       *     "scope2"
       *   ]
       * }
       */
      context?: {
        [key: string]: string[]
      }
      /** @description A human readable message describing the error along with remediation steps where appropriate */
      message: string
    }
    CollectionResponseExternalUnifiedEvent: {
      paging?: components['schemas']['Paging']
      results: components['schemas']['ExternalUnifiedEvent'][]
    }
    /**
     * @description Used to represent any event. With this format, the `objectType` and `eventType` values are stringified CRM types. Example object:
     * <br/>
     * ```
     *  {
     *       "objectType": "CONTACT",
     *       "objectId": 208451632,
     *       "eventType": "e_visited_page",
     *       "occurredAt": 1567377501421,
     *       "id": "leviathan-be3335d3-46f1-3985-988e-ff38e6e7b9d8",
     *       "properties": {
     *           "hs_url": "https://some-website.com/",
     *           "hs_title": "Home",
     *           "hs_referrer": "https://some-other-website.com/blog/why-we-love-big-data-and-you-should-too",
     *           "hs_userAgent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36",
     *           "hs_city": "lund",
     *           "hs_region": "m",
     *           "hs_country": "se",
     *           "hs_session_id" : "leviathan-be3335d3-46f1-3985-988e-ff38e6e7b9d8",
     *           "hs_session_source" : "DIRECT"
     *       }
     *   }
     * ```
     */
    ExternalUnifiedEvent: {
      /**
       * Format: date-time
       * @description An ISO 8601 timestamp when the event occurred.
       */
      occurredAt: string
      /** @description The format of the `eventType` string is `ae{appId}_{eventTypeLabel}`, `pe{portalId}_{eventTypeLabel}`, or just `e_{eventTypeLabel}` for HubSpot events. */
      eventType: string
      /** @description A unique identifier for the event. */
      id: string
      /** @description The objectId of the object which did the event. */
      objectId: string
      properties?: {
        [key: string]: string
      }
      /** @description The objectType for the object which did the event. */
      objectType: string
    }
    PreviousPage: {
      before: string
      link?: string
    }
    Paging: {
      next?: components['schemas']['NextPage']
      prev?: components['schemas']['PreviousPage']
    }
    /**
     * @example {
     *   "message": "Invalid input (details will vary based on the error)",
     *   "correlationId": "aeb5f871-7f07-4993-9211-075dc63e7cbf",
     *   "category": "VALIDATION_ERROR",
     *   "links": {
     *     "knowledge-base": "https://www.hubspot.com/products/service/knowledge-base"
     *   }
     * }
     */
    Error: {
      /** @description A specific category that contains more specific detail about the error */
      subCategory?: string
      /**
       * @description Context about the error condition
       * @example {
       *   "missingScopes": [
       *     "scope1",
       *     "scope2"
       *   ],
       *   "invalidPropertyName": [
       *     "propertyValue"
       *   ]
       * }
       */
      context?: {
        [key: string]: string[]
      }
      /**
       * Format: uuid
       * @description A unique identifier for the request. Include this value with any error reports or support tickets
       * @example aeb5f871-7f07-4993-9211-075dc63e7cbf
       */
      correlationId: string
      /**
       * @description A map of link names to associated URIs containing documentation about the error or recommended remediation steps
       * @example {
       *   "knowledge-base": "https://www.hubspot.com/products/service/knowledge-base"
       * }
       */
      links?: {
        [key: string]: string
      }
      /**
       * @description A human readable message describing the error along with remediation steps where appropriate
       * @example Invalid input (details will vary based on the error)
       */
      message: string
      /**
       * @description The error category
       * @example VALIDATION_ERROR
       */
      category: string
      /** @description further information about the error */
      errors?: components['schemas']['ErrorDetail'][]
    }
    NextPage: {
      link?: string
      after: string
    }
  }
  responses: {
    /** @description An error occurred. */
    Error: {
      content: {
        '*/*': components['schemas']['Error']
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  'get-/events/v3/events/_getPage': {
    parameters: {
      query?: {
        objectType?: string
        eventType?: string
        occurredAfter?: string
        occurredBefore?: string
        objectId?: number
        indexTableName?: string
        indexSpecificMetadata?: string
        /** @description The paging cursor token of the last successfully read resource will be returned as the `paging.next.after` JSON property of a paged response containing more results. */
        after?: string
        before?: string
        /** @description The maximum number of results to display per page. */
        limit?: number
        sort?: string[]
        'objectProperty.{propname}'?: Record<string, never>
        'property.{propname}'?: Record<string, never>
        id?: string[]
      }
    }
    responses: {
      /** @description successful operation */
      200: {
        content: {
          'application/json': components['schemas']['CollectionResponseExternalUnifiedEvent']
        }
      }
      default: components['responses']['Error']
    }
  }
}

export interface oasTypes {
  components: components
  external: external
  operations: operations
  paths: paths
  webhooks: webhooks
}

export default oasTypes
