/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/crm/v3/extensions/videoconferencing/settings/{appId}': {
    /**
     * Get settings
     * @description Return the settings for a video conference application with the specified ID.
     */
    get: operations['get-/crm/v3/extensions/videoconferencing/settings/{appId}_getById']
    /**
     * Update settings
     * @description Updates the settings for a video conference application with the specified ID.
     */
    put: operations['put-/crm/v3/extensions/videoconferencing/settings/{appId}_replace']
    /**
     * Delete settings
     * @description Deletes the settings for a video conference application with the specified ID.
     */
    delete: operations['delete-/crm/v3/extensions/videoconferencing/settings/{appId}_archive']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    ErrorDetail: {
      /** @description A specific category that contains more specific detail about the error */
      subCategory?: string
      /** @description The status code associated with the error detail */
      code?: string
      /** @description The name of the field or parameter in which the error was found. */
      in?: string
      /**
       * @description Context about the error condition
       * @example {
       *   "missingScopes": [
       *     "scope1",
       *     "scope2"
       *   ]
       * }
       */
      context?: {
        [key: string]: string[]
      }
      /** @description A human readable message describing the error along with remediation steps where appropriate */
      message: string
    }
    /**
     * @example {
     *   "message": "Invalid input (details will vary based on the error)",
     *   "correlationId": "aeb5f871-7f07-4993-9211-075dc63e7cbf",
     *   "category": "VALIDATION_ERROR",
     *   "links": {
     *     "knowledge-base": "https://www.hubspot.com/products/service/knowledge-base"
     *   }
     * }
     */
    Error: {
      /** @description A specific category that contains more specific detail about the error */
      subCategory?: string
      /**
       * @description Context about the error condition
       * @example {
       *   "missingScopes": [
       *     "scope1",
       *     "scope2"
       *   ],
       *   "invalidPropertyName": [
       *     "propertyValue"
       *   ]
       * }
       */
      context?: {
        [key: string]: string[]
      }
      /**
       * Format: uuid
       * @description A unique identifier for the request. Include this value with any error reports or support tickets
       * @example aeb5f871-7f07-4993-9211-075dc63e7cbf
       */
      correlationId: string
      /**
       * @description A map of link names to associated URIs containing documentation about the error or recommended remediation steps
       * @example {
       *   "knowledge-base": "https://www.hubspot.com/products/service/knowledge-base"
       * }
       */
      links?: {
        [key: string]: string
      }
      /**
       * @description A human readable message describing the error along with remediation steps where appropriate
       * @example Invalid input (details will vary based on the error)
       */
      message: string
      /**
       * @description The error category
       * @example VALIDATION_ERROR
       */
      category: string
      /** @description further information about the error */
      errors?: components['schemas']['ErrorDetail'][]
    }
    /**
     * @description The URLs of the various actions provided by the video conferencing application. All URLs must use the `https` protocol.
     * @example {
     *   "createMeetingUrl": "https://example.com/create-meeting",
     *   "updateMeetingUrl": "https://example.com/update-meeting",
     *   "deleteMeetingUrl": "https://example.com/delete-meeting",
     *   "userVerifyUrl": "https://example.com/user-verify"
     * }
     */
    ExternalSettings: {
      /**
       * @description The URL that HubSpot will use to verify that a user exists in the video conference application.
       * @example https://example.com/user-verify
       */
      userVerifyUrl?: string
      fetchAccountsUri?: string
      /**
       * @description The URL that HubSpot will send requests to create a new video conference.
       * @example https://example.com/create-meeting
       */
      createMeetingUrl: string
      /**
       * @description The URL that HubSpot will send updates to existing meetings. Typically called when the user changes the topic or times of a meeting.
       * @example https://example.com/update-meeting
       */
      updateMeetingUrl?: string
      /**
       * @description The URL that HubSpot will send notifications of meetings that have been deleted in HubSpot.
       * @example https://example.com/delete-meeting
       */
      deleteMeetingUrl?: string
    }
  }
  responses: {
    /** @description An error occurred. */
    Error: {
      content: {
        '*/*': components['schemas']['Error']
      }
    }
  }
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  /**
   * Get settings
   * @description Return the settings for a video conference application with the specified ID.
   */
  'get-/crm/v3/extensions/videoconferencing/settings/{appId}_getById': {
    parameters: {
      path: {
        /** @description The ID of the video conference application. This is the identifier of the application created in your HubSpot developer portal. */
        appId: number
      }
    }
    responses: {
      /** @description successful operation */
      200: {
        content: {
          'application/json': components['schemas']['ExternalSettings']
        }
      }
      default: components['responses']['Error']
    }
  }
  /**
   * Update settings
   * @description Updates the settings for a video conference application with the specified ID.
   */
  'put-/crm/v3/extensions/videoconferencing/settings/{appId}_replace': {
    parameters: {
      path: {
        /** @description The ID of the video conference application. This is the identifier of the application created in your HubSpot developer portal. */
        appId: number
      }
    }
    requestBody: {
      content: {
        'application/json': components['schemas']['ExternalSettings']
      }
    }
    responses: {
      /** @description successful operation */
      200: {
        content: {
          'application/json': components['schemas']['ExternalSettings']
        }
      }
      default: components['responses']['Error']
    }
  }
  /**
   * Delete settings
   * @description Deletes the settings for a video conference application with the specified ID.
   */
  'delete-/crm/v3/extensions/videoconferencing/settings/{appId}_archive': {
    parameters: {
      path: {
        /** @description The ID of the video conference application. This is the identifier of the application created in your HubSpot developer portal. */
        appId: number
      }
    }
    responses: {
      /** @description No content */
      204: {
        content: {}
      }
      default: components['responses']['Error']
    }
  }
}

export interface oasTypes {
  components: components
  external: external
  operations: operations
  paths: paths
  webhooks: webhooks
}

export default oasTypes
