// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    title: 'Webhooks API',
    description:
      '\nBrex uses webhooks to send real-time notifications when events happen in the accounts that you manage.\nUse webhook subscriptions to subscribe to different webhook events.\n',
    contact: {
      name: 'Admin',
      url: 'https://brex.com',
      email: 'developer-access@brex.com',
    },
    version: '0.1',
  },
  servers: [
    {url: 'https://platform.brexapis.com', description: 'Production'},
    {
      url: 'https://platform.staging.brexapps.com',
      description:
        'Staging (Note: This is not a sandbox. It will not work with customer tokens.)',
    },
  ],
} as const
export default oasMeta
