// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    contact: {
      email: 'dev-platform@stripe.com',
      name: 'Stripe Dev Platform Team',
      url: 'https://stripe.com',
    },
    description:
      'The Stripe REST API. Please see https://stripe.com/docs/api for more details.',
    termsOfService: 'https://stripe.com/us/terms/',
    title: 'Stripe API',
    version: '2024-04-10',
    'x-stripeSpecFilename': 'spec3',
  },
  servers: [{url: 'https://api.stripe.com/'}],
} as const
export default oasMeta
