{
  "openapi": "3.0.1",
  "info": {
    "title": "Team API",
    "description": "\nThe team API lets you manage users, departments, locations, and cards.\n",
    "contact": {
      "name": "Admin",
      "url": "https://brex.com",
      "email": "developer-access@brex.com"
    },
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://platform.brexapis.com",
      "description": "Production"
    },
    {
      "url": "https://platform.staging.brexapps.com",
      "description": "Staging (Note: This is not a sandbox. It will not work with customer tokens.)"
    }
  ],
  "security": [
    {
      "OAuth2": []
    }
  ],
  "tags": [
    {
      "name": "Users",
      "description": "Endpoints for user management."
    },
    {
      "name": "Locations",
      "description": "Endpoints for location management."
    },
    {
      "name": "Departments",
      "description": "Endpoints for department management."
    },
    {
      "name": "Titles",
      "description": "Endpoints for title management."
    },
    {
      "name": "Cards",
      "description": "Endpoints for card management."
    }
  ],
  "paths": {
    "/v2/cards": {
      "get": {
        "tags": [
          "Cards"
        ],
        "summary": "\nList cards\n",
        "description": "\nLists all cards by a `user_id`.\nOnly cards with `limit_type = CARD` have `spend_controls`\n",
        "operationId": "listCardsByUserId",
        "security": [
          {
            "OAuth2": [
              "cards.readonly",
              "cards"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "\nCreate card\n",
        "description": "\nCreates a new card.\nThe `spend_controls` field is required when `limit_type` = `CARD`.\nThe `mailing_address` field is required for physical cards and is the shipping address used to send the card; it is not the same as the billing and mailing address used for online purchases.\nThe first 2 lines of this address must be under 60 characters long. Each user can only have up to 10 active physical cards.\nFor Empower accounts, this endpoint requires budget management. If y[...]",
        "operationId": "createCard",
        "security": [
          {
            "OAuth2": [
              "cards"
            ]
          }
        ]
      }
    },
    "/v2/cards/{id}": {
      "get": {
        "tags": [
          "Cards"
        ],
        "summary": "\nGet card\n",
        "description": "\nRetrieves a card by ID. Only cards with `limit_type = CARD` have `spend_controls`\n",
        "operationId": "getCardById",
        "security": [
          {
            "OAuth2": [
              "cards",
              "cards.readonly"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Cards"
        ],
        "summary": "\nUpdate card\n",
        "description": "\nUpdate an existing vendor card\n",
        "operationId": "updateCard",
        "security": [
          {
            "OAuth2": [
              "cards"
            ]
          }
        ]
      }
    },
    "/v2/cards/{id}/lock": {
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "\nLock card\n",
        "description": "\nLocks an existing, unlocked card. And the card owner will receive a notification about it.\n",
        "operationId": "lockCard",
        "security": [
          {
            "OAuth2": [
              "cards"
            ]
          }
        ]
      }
    },
    "/v2/cards/{id}/pan": {
      "get": {
        "tags": [
          "Cards"
        ],
        "summary": "\nGet card number\n",
        "description": "\nRetrieves card number, CVV, and expiration date of a card by ID.\n",
        "operationId": "getCardNumber",
        "security": [
          {
            "OAuth2": [
              "cards.pan"
            ]
          }
        ],
        "servers": [
          {
            "url": "https://secure-platform.brexapis.com",
            "description": "Production"
          },
          {
            "url": "https://secure-platform.staging.brexapps.com",
            "description": "Staging (Note: This is not a sandbox. It will not work with customer tokens.)"
          }
        ]
      }
    },
    "/v2/cards/{id}/secure_email": {
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "\nCreate secure email to send card number \n",
        "description": "\nCreates a secure email to send card number, CVV, and expiration date of a card by ID to the specified email.\n\nThis endpoint is currently gated. If you would like to request access, please reach out to\ndeveloper-access@brex.com\n",
        "operationId": "emailCardNumber",
        "security": [
          {
            "OAuth2": [
              "cards.pan"
            ]
          }
        ]
      }
    },
    "/v2/cards/{id}/terminate": {
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "\nTerminate card\n",
        "description": "\nTerminates an existing card. The card owner will receive a notification about it.\n",
        "operationId": "terminateCard",
        "security": [
          {
            "OAuth2": [
              "cards"
            ]
          }
        ]
      }
    },
    "/v2/cards/{id}/unlock": {
      "post": {
        "tags": [
          "Cards"
        ],
        "summary": "\nUnlock card\n",
        "description": "\nUnlocks an existing card.\n",
        "operationId": "unlockCard",
        "security": [
          {
            "OAuth2": [
              "cards"
            ]
          }
        ]
      }
    },
    "/v2/company": {
      "get": {
        "tags": [
          "Companies"
        ],
        "summary": "\nGet company\n",
        "description": "\nThis endpoint returns the company associated with the OAuth2 access token.\n",
        "operationId": "getCompany",
        "security": [
          {
            "OAuth2": [
              "companies.readonly"
            ]
          }
        ]
      }
    },
    "/v2/departments": {
      "get": {
        "tags": [
          "Departments"
        ],
        "summary": "\nList departments\n",
        "description": "\nThis endpoint lists all departments.\n",
        "operationId": "listDepartments",
        "security": [
          {
            "OAuth2": [
              "departments",
              "departments.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Departments"
        ],
        "summary": "\nCreate department\n",
        "description": "\nThis endpoint creates a new department\n",
        "operationId": "createDepartment",
        "security": [
          {
            "OAuth2": [
              "departments"
            ]
          }
        ]
      }
    },
    "/v2/departments/{id}": {
      "get": {
        "tags": [
          "Departments"
        ],
        "summary": "\nGet department\n",
        "description": "\nThis endpoint gets a department by ID.\n",
        "operationId": "getDepartmentById",
        "security": [
          {
            "OAuth2": [
              "departments",
              "departments.readonly"
            ]
          }
        ]
      }
    },
    "/v2/locations": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "\nList locations\n",
        "description": "\nThis endpoint lists all locations.\n",
        "operationId": "listLocations",
        "security": [
          {
            "OAuth2": [
              "locations",
              "locations.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Locations"
        ],
        "summary": "\nCreate location\n",
        "description": "\nThis endpoint creates a new location.\n",
        "operationId": "createLocation",
        "security": [
          {
            "OAuth2": [
              "locations"
            ]
          }
        ]
      }
    },
    "/v2/locations/{id}": {
      "get": {
        "tags": [
          "Locations"
        ],
        "summary": "\nGet location\n",
        "description": "\nThis endpoint gets a location by ID.\n",
        "operationId": "getLocationById",
        "security": [
          {
            "OAuth2": [
              "locations",
              "locations.readonly"
            ]
          }
        ]
      }
    },
    "/v2/titles": {
      "get": {
        "tags": [
          "Titles"
        ],
        "summary": "\nList titles\n",
        "description": "\nThis endpoint lists all titles.\n",
        "operationId": "listTitles",
        "security": [
          {
            "OAuth2": [
              "titles",
              "titles.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Titles"
        ],
        "summary": "\nCreate title\n",
        "description": "\nThis endpoint creates a new title\n",
        "operationId": "createTitle",
        "security": [
          {
            "OAuth2": [
              "titles"
            ]
          }
        ]
      }
    },
    "/v2/titles/{id}": {
      "get": {
        "tags": [
          "Titles"
        ],
        "summary": "\nGet title\n",
        "description": "\nThis endpoint gets a title by ID.\n",
        "operationId": "getTitleById",
        "security": [
          {
            "OAuth2": [
              "titles",
              "titles.readonly"
            ]
          }
        ]
      }
    },
    "/v2/users": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "\nList users\n",
        "description": "\nThis endpoint lists all users. To find a user id by email, you can filter using the `email` query parameter.\n",
        "operationId": "listUsers",
        "security": [
          {
            "OAuth2": [
              "users",
              "users.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "\nInvite user\n",
        "description": "\nThis endpoint invites a new user as an employee.\nTo update user's role, check out [this article](https://support.brex.com/how-do-i-change-another-user-s-role/).\n",
        "operationId": "createUser",
        "security": [
          {
            "OAuth2": [
              "users"
            ]
          }
        ]
      }
    },
    "/v2/users/me": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "\nGet current user\n",
        "description": "\nThis endpoint returns the user associated with the OAuth2 access token.\n",
        "operationId": "getMe",
        "security": [
          {
            "OAuth2": [
              "users",
              "users.readonly"
            ]
          }
        ]
      }
    },
    "/v2/users/{id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "\nGet user\n",
        "description": "\nThis endpoint gets a user by ID.\n",
        "operationId": "getUserById",
        "security": [
          {
            "OAuth2": [
              "users",
              "users.readonly"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "\nUpdate user\n",
        "description": "\nThis endpoint updates a user. Any parameters not provided will be left unchanged.\n",
        "operationId": "updateUser",
        "security": [
          {
            "OAuth2": [
              "users"
            ]
          }
        ]
      }
    },
    "/v2/users/{id}/limit": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "\nGet limit for the user\n",
        "description": "\nThis endpoint gets the monthly limit for the user including the monthly available limit.\n",
        "operationId": "getUserLimit",
        "security": [
          {
            "OAuth2": [
              "users",
              "users.readonly"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "\nSet limit for the user\n",
        "description": "\nThis endpoint sets the monthly limit for a user. \nThe limit amount must be non-negative. \nTo unset the monthly limit of the user, just set `monthly_limit` to null.\n",
        "operationId": "setUserLimit",
        "security": [
          {
            "OAuth2": [
              "users"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "description": "OAuth2 security scheme",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts-api.brex.com/oauth2/default/v1/authorize",
            "tokenUrl": "https://accounts-api.brex.com/oauth2/default/v1/token",
            "scopes": {
              "openid": "openid",
              "offline_access": "offline access",
              "users.readonly": "View user data",
              "users": "View and manage user data",
              "locations.readonly": "View location data",
              "locations": "View and manage location data",
              "departments.readonly": "View department data",
              "departments": "View and manage department data",
              "titles": "View and manage title data",
              "titles.readonly": "View title data",
              "cards": "View and manage card data",
              "cards.readonly": "View card data",
              "cards.pan": "View and Send card number data"
            }
          }
        }
      }
    }
  },
  "x-explorer-enabled": false
}