{
  "openapi": "3.0.1",
  "info": {
    "title": "Budgets API",
    "description": "\nThe budgets API lets you manage your Brex budgets.\n",
    "contact": {
      "name": "Admin",
      "url": "https://brex.com",
      "email": "developer-access@brex.com"
    },
    "version": "1.0"
  },
  "servers": [
    {
      "url": "https://platform.brexapis.com",
      "description": "Production"
    },
    {
      "url": "https://platform.staging.brexapps.com",
      "description": "Staging (Note: This is not a sandbox. It will not work with customer tokens.)"
    }
  ],
  "security": [
    {
      "OAuth2": []
    }
  ],
  "tags": [
    {
      "name": "Budgets",
      "description": "Endpoints for budgets data."
    },
    {
      "name": "Budget Programs",
      "description": "Endpoints for budgets programs data."
    }
  ],
  "paths": {
    "/v1/budget_programs": {
      "get": {
        "tags": [
          "Budget Programs"
        ],
        "summary": "\nList Budget Programs\n",
        "description": "\nLists Budget Programs belonging to this account\n",
        "operationId": "listBudgetPrograms",
        "security": [
          {
            "OAuth2": [
              "budgets.readonly",
              "budgets"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Budget Programs"
        ],
        "summary": "\nCreate Budget Program\n",
        "description": "\nCreates a Budget Program.\nIf your account does not have access to budget program features, a 403 response status will be returned.\nIf this is the case and you want to gain access to this endpoint, please contact Brex support.\n",
        "operationId": "createBudgetProgram",
        "security": [
          {
            "OAuth2": [
              "budgets"
            ]
          }
        ]
      }
    },
    "/v1/budget_programs/{id}": {
      "get": {
        "tags": [
          "Budget Programs"
        ],
        "summary": "\nGet Budget Program\n",
        "description": "\nRetrieves a Budget Program by ID\n",
        "operationId": "getBudgetProgramById",
        "security": [
          {
            "OAuth2": [
              "budgets.readonly",
              "budgets"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Budget Programs"
        ],
        "summary": "\nUpdate Budget Program\n",
        "description": "\nUpdates a Budget Program.\nThis endpoint requires budget management. If your account does not have access to budget management features, a 403 response status will be returned. \nIf this is the case and you want to gain access to this endpoint, please contact Brex support.\n",
        "operationId": "updateBudgetProgram",
        "security": [
          {
            "OAuth2": [
              "budgets"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Budget Programs"
        ],
        "summary": "\nDelete Budget Program\n",
        "description": "\nDelete a Budget Program by ID.\nThis endpoint requires budget management. If your account does not have access to budget management features, a 403 response status will be returned. \nIf this is the case and you want to gain access to this endpoint, please contact Brex support.\n",
        "operationId": "deleteBudgetProgram",
        "security": [
          {
            "OAuth2": [
              "budgets"
            ]
          }
        ]
      }
    },
    "/v1/budgets": {
      "get": {
        "tags": [
          "Budgets"
        ],
        "summary": "\nList Budgets\n",
        "description": "\nLists Budgets belonging to this account\n",
        "operationId": "listBudgets",
        "security": [
          {
            "OAuth2": [
              "budgets.readonly",
              "budgets"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Budgets"
        ],
        "summary": "\nCreate Budget\n",
        "description": "\nCreates a Budget.\nThis endpoint requires budget management. If your account does not have access to budget management features, a 403 response status will be returned. \nIf this is the case and you want to gain access to this endpoint, please contact Brex support.\n",
        "operationId": "createBudget",
        "security": [
          {
            "OAuth2": [
              "budgets"
            ]
          }
        ]
      }
    },
    "/v1/budgets/{id}": {
      "get": {
        "tags": [
          "Budgets"
        ],
        "summary": "\nGet Budget\n",
        "description": "\nRetrieves a Budget by ID\n",
        "operationId": "getBudgetById",
        "security": [
          {
            "OAuth2": [
              "budgets.readonly",
              "budgets"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Budgets"
        ],
        "summary": "\nUpdate Budget\n",
        "description": "\nUpdates a Budget.\nThis endpoint requires budget management. If your account does not have access to budget management features, a 403 response status will be returned. \nIf this is the case and you want to gain access to this endpoint, please contact Brex support.\n",
        "operationId": "updateBudget",
        "security": [
          {
            "OAuth2": [
              "budgets"
            ]
          }
        ]
      }
    },
    "/v1/budgets/{id}/archive": {
      "post": {
        "tags": [
          "Budgets"
        ],
        "summary": "\nArchive a budget\n",
        "description": "\nArchives a budget, making it unusable for future expenses and removing it from the UI\n",
        "operationId": "archiveBudget",
        "security": [
          {
            "OAuth2": [
              "budgets"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "description": "OAuth2 security scheme",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts-api.brex.com/oauth2/default/v1/authorize",
            "tokenUrl": "https://accounts-api.brex.com/oauth2/default/v1/token",
            "scopes": {
              "openid": "openid",
              "offline_access": "offline access",
              "budgets": "View and manage budgets data",
              "budgets.readonly": "View budgets data"
            }
          }
        }
      }
    }
  },
  "x-explorer-enabled": false
}