/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/payments/open-va/retrieve/VA-ID={VA-ID}': {
    /** Status of open VA */
    get: operations['status-of-open-va']
  }
  '/payments/open-va/status/{VA-ID}': {
    /**
     * Simulate payment of open VA [PAID]
     * @description This API is for simulation to test the open VA process, This API is only available in a Sandbox environment.
     */
    post: operations['simulate-payment-of-open-va']
  }
  '/payments/close-va/status/{VA-ID}': {
    /**
     * Simulate payment of close VA [PAID]
     * @description This API is for simulation to test the open VA process, This API is only available in a Sandbox environment.
     */
    post: operations['simulate-payment-of-close-va']
  }
  '/auth/': {
    /** Generate OTP in GoPay */
    post: operations['generate-otp-in-gopay']
  }
  '/auth///': {
    /** Generate OTP in MyBCA */
    post: operations['generate-otp-in-mybca']
  }
  '/auth//': {
    /** Generate OTP in OCBC Mobile */
    post: operations['generate-otp-in-ocbc']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  /** Status of open VA */
  'status-of-open-va': {
    parameters: {
      header: {
        /** @description Unique token for clients(Public access token) */
        Authorization: string
      }
      path: {
        /** @description Unique id of virtual account */
        'VA-ID': string
      }
    }
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 200
             */
            status?: number
            /** @example OK */
            message?: string
            data?: {
              /** @example OP_d8ed71ed64d64b2fa220ab5d86f2fe35 */
              id?: string
              /** @example virtual_bank_account */
              type?: string
              attributes?: {
                /** @example test_VA1 */
                referenceId?: string
                instructions?: {
                  /** @example BRI */
                  bankShortCode?: string
                  /** @example 130432138889902 */
                  accountNo?: string
                  /** @example IKN-Open VA 1 */
                  displayName?: string
                }
              }
            }
          }
        }
      }
      /** @description 401 */
      401: {
        content: {
          'text/plain': {
            /**
             * @default 0
             * @example 401
             */
            status?: number
            /** @example Unauthorized */
            message?: string
            /** @example Transaction ID not found */
            data?: string
          }
        }
      }
    }
  }
  /**
   * Simulate payment of open VA [PAID]
   * @description This API is for simulation to test the open VA process, This API is only available in a Sandbox environment.
   */
  'simulate-payment-of-open-va': {
    parameters: {
      query: {
        /** @description The status that want to be achieved (paid / completed) */
        action: string
      }
      header: {
        /** @description Unique token for clients */
        Authorization: string
      }
      path: {
        /** @description ID of VA that is generated by Brick in the VA generation API response for simulating "paid" status, ID of Payment that is generated by Brick in the VA callback response for simulating "completed" status */
        'VA-ID': string
      }
    }
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 200
             */
            status?: number
            /** @example OK */
            message?: string
            data?: unknown
          }
        }
      }
    }
  }
  /**
   * Simulate payment of close VA [PAID]
   * @description This API is for simulation to test the open VA process, This API is only available in a Sandbox environment.
   */
  'simulate-payment-of-close-va': {
    parameters: {
      query: {
        /** @description The status that want to be achieved (paid / completed) */
        action: string
      }
      header: {
        /** @description Unique token for clients(Public access token) */
        Authorization: string
      }
      path: {
        /** @description ID of VA that is generated by Brick in the VA generation API response for simulating "paid" status, ID of Payment that is generated by Brick in the VA callback response for simulating "completed" status */
        'VA-ID': string
      }
    }
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 200
             */
            status?: number
            /** @example OK */
            message?: string
            data?: unknown
          }
        }
      }
    }
  }
  /** Generate OTP in GoPay */
  'generate-otp-in-gopay': {
    parameters: {
      header: {
        /** @description Unique identifier for client(Public access token) */
        Authorization: string
      }
    }
    requestBody?: {
      content: {
        'application/json': {
          /** @description ID of the institution */
          institution_id: string
          /** @description End-user's Gopay registered mobile number (e.g. +628122323123) */
          username: string
        }
      }
    }
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 200
             */
            status?: number
            /** @example OK */
            message?: string
            data?: {
              /** @example +62812345678 */
              username?: string
              /** @example 308AF96B-04B8-475D-A17C-F457FFE4DC56 */
              uniqueId?: string
              /** @example 1E45F913-64E9-4325-BFD5-7EF7C131BE4C */
              sessionId?: string
              /** @example d8dc5eb5-b707-4168-900f-de2bb3f8022f */
              otpToken?: string
            }
          }
        }
      }
      /** @description 401 */
      401: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 401
             */
            status?: number
            /** @example Unauthorized */
            message?: string
            /** @example Mobile number is not registered */
            data?: string
          }
        }
      }
    }
  }
  /** Generate OTP in MyBCA */
  'generate-otp-in-mybca': {
    parameters: {
      header: {
        /** @description Unique identifier for client(Public access token) */
        Authorization: string
      }
    }
    requestBody?: {
      content: {
        'application/json': {
          /** @description ID of the institution */
          institution_id: string
          /** @description End-user's MyBCA username account */
          username: string
        }
      }
    }
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 428
             */
            status?: number
            /** @example An OTP is required by the institution to login */
            message?: string
            data?: {
              /** @example f008feb2-7931-4711-85c1-d044141c96a3-20240320122648 */
              sessionId?: string
              /** @example username */
              username?: string
              /** @example 120000 */
              duration?: string
            }
          }
        }
      }
      /** @description 401 */
      401: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 401
             */
            status?: number
            /** @example Unauthorized */
            message?: string
            /** @example Username is not registered */
            data?: string
          }
        }
      }
    }
  }
  /** Generate OTP in OCBC Mobile */
  'generate-otp-in-ocbc': {
    parameters: {
      header: {
        /** @description Unique identifier for client(Public access token) */
        Authorization: string
      }
    }
    requestBody?: {
      content: {
        'application/json': {
          /** @description ID of the institution */
          institution_id: string
          /** @description End-user's OCBC username account */
          username: string
        }
      }
    }
    responses: {
      /** @description 200 */
      200: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 428
             */
            status?: number
            /** @example An OTP is required by the institution to login */
            message?: string
            data?: {
              /** @example f008feb2-7931-4711-85c1-d044141c96a3-20240320122648 */
              sessionId?: string
              /** @example username */
              username?: string
              /** @example 120000 */
              duration?: string
            }
          }
        }
      }
      /** @description 401 */
      401: {
        content: {
          'application/json': {
            /**
             * @default 0
             * @example 401
             */
            status?: number
            /** @example Unauthorized */
            message?: string
            /** @example Username is not registered */
            data?: string
          }
        }
      }
    }
  }
}

export interface oasTypes {
  components: components
  external: external
  operations: operations
  paths: paths
  webhooks: webhooks
}

export default oasTypes
