/**
 * This file was generated by @opensdks/cli, do not edit manually.
 * For bugs & feature requests, please open an issue on the [GitHub](https://github.com/tonyxiao/openSDKs)
 */

import type {
  ClientOptions,
  OpenAPITypes,
  SdkDefinition,
  SDKTypes,
} from '@opensdks/runtime'
import {initSDK} from '@opensdks/runtime'
import type Oas_oauth2_v1 from '../mercury_oauth2_v1.oas.types.js'
import type Oas_v1 from '../mercury_v1.oas.types.js'
import type Oas_v2 from '../mercury_v2.oas.types.js'
import {default as oas_oauth2_v1} from './mercury_oauth2_v1.oas.meta.js'
import {default as oas_v1} from './mercury_v1.oas.meta.js'
import {default as oas_v2} from './mercury_v2.oas.meta.js'

export type {Oas_oauth2_v1, Oas_v1, Oas_v2}

export {oas_oauth2_v1, oas_v1, oas_v2}

export type MercurySDKTypes = SDKTypes<OpenAPITypes, ClientOptions>

export const mercurySdkDef = {
  types: {} as MercurySDKTypes,
  defaultOptions: {},
  createClient(ctx, options) {
    const oauth2_v1 = ctx.createClient<Oas_oauth2_v1['paths']>({
      ...options,
      baseUrl: options.baseUrl ?? oas_oauth2_v1.servers[0]?.url,
    })
    const v1 = ctx.createClient<Oas_v1['paths']>({
      ...options,
      baseUrl: options.baseUrl ?? oas_v1.servers[0]?.url,
    })
    const v2 = ctx.createClient<Oas_v2['paths']>({
      ...options,
      baseUrl: options.baseUrl ?? oas_v2.servers[0]?.url,
    })

    return {
      oauth2_v1,
      v1,
      v2,
    }
  },
} satisfies SdkDefinition<MercurySDKTypes>

export function initMercurySDK(opts: MercurySDKTypes['options']) {
  return initSDK(mercurySdkDef, opts)
}

export type MercurySDK = ReturnType<typeof initMercurySDK>

export default initMercurySDK
