// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {title: 'OAuth2', version: '1'},
  servers: [{url: 'https://oauth2.mercury.com/'}],
} as const
export default oasMeta
