// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {title: 'Quickbooks API', version: '0.0.0'},
  servers: [
    {
      url: 'https://quickbooks.api.intuit.com/v3/company/{realmId}',
      description: 'production',
      variables: {realmId: {default: ''}},
    },
    {
      description: 'sandbox',
      url: 'https://sandbox-quickbooks.api.intuit.com/v3/company/{realmId}',
      variables: {realmId: {default: ''}},
    },
  ],
} as const
export default oasMeta
