/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/postings/{id}': {
    get: operations['getPosting']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: {
    posting: {
      id: string
      text: string
      createdAt: number
      updatedAt: number
      user: string
      owner: string
      hiringManager: string
      /** @enum {string} */
      confidentiality: 'non-confidential'
      categories: {
        team: string
        department: string
        location: string
        allLocations: string[]
        commitment: string
        level: string
      }
      content: {
        description: string
        descriptionHtml: string
        lists: {
          text: string
          content: string
        }[]
        closing: string
        closingHtml: string
      }
      country: string
      tags: string[]
      /** @enum {string} */
      state: 'published'
      distributionChannels: ('internal' | 'public')[]
      reqCode: string
      requisitionCodes: string[]
      salaryDescription: string
      salaryDescriptionHtml: string
      salaryRange: {
        max: number
        min: number
        currency: string
        /** @enum {string} */
        interval: 'per-year-salary'
      }
      urls: {
        /** Format: uri */
        list: string
        /** Format: uri */
        show: string
        /** Format: uri */
        apply: string
      }
      /** @enum {string} */
      workplaceType: 'remote'
      [key: string]: unknown
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  getPosting: {
    parameters: {
      path: {
        /** @description The ID of the posting to retrieve */
        id: string
      }
    }
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': components['schemas']['posting']
        }
      }
    }
  }
}

export interface oasTypes {
  components: components
  external: external
  operations: operations
  paths: paths
  webhooks: webhooks
}

export default oasTypes
