// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    version: '3.0.1',
    title: 'Xero Payroll NZ',
    description: 'This is the Xero Payroll API for orgs in the NZ region.',
    termsOfService:
      'https://developer.xero.com/xero-developer-platform-terms-conditions/',
    contact: {
      name: 'Xero Platform Team',
      email: 'api@xero.com',
      url: 'https://developer.xero.com',
    },
  },
  servers: [
    {
      description: 'Xero Payroll NZ API',
      url: 'https://api.xero.com/payroll.xro/2.0',
    },
  ],
} as const
export default oasMeta
