// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    version: '3.0.1',
    title: 'Xero Bank Feeds API',
    description:
      "The Bank Feeds API is a closed API that is only available to financial institutions that have an established financial services partnership with Xero. If you're an existing financial services partner that wants access, contact your local Partner Manager. If you're a financial institution who wants to provide bank feeds to your business customers, contact us to become a financial services partner.",
    termsOfService:
      'https://developer.xero.com/xero-developer-platform-terms-conditions/',
    contact: {
      name: 'Xero Platform Team',
      email: 'api@xero.com',
      url: 'https://developer.xero.com',
    },
    license: {
      name: 'MIT',
      url: 'https://github.com/XeroAPI/Xero-OpenAPI/blob/master/LICENSE',
    },
  },
  servers: [
    {
      description: 'Xero Bank Feeds API base url',
      url: 'https://api.xero.com/bankfeeds.xro/1.0',
    },
  ],
} as const
export default oasMeta
