// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    title: 'Xero Accounting API',
    version: '3.0.1',
    termsOfService:
      'https://developer.xero.com/xero-developer-platform-terms-conditions/',
    contact: {
      name: 'Xero Platform Team',
      email: 'api@xero.com',
      url: 'https://developer.xero.com',
    },
  },
  servers: [
    {
      description:
        'The Xero Accounting API exposes accounting and related functions of the main Xero application and can be used for a variety of purposes such as creating transactions like invoices and credit notes, right through to extracting accounting data via our reports endpoint.',
      url: 'https://api.xero.com/api.xro/2.0',
    },
  ],
} as const
export default oasMeta
