// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    title: 'Xero Files API',
    version: '3.0.1',
    description: 'These endpoints are specific to Xero Files API',
    termsOfService:
      'https://developer.xero.com/xero-developer-platform-terms-conditions/',
    contact: {
      name: 'Xero Platform Team',
      email: 'api@xero.com',
      url: 'https://developer.xero.com',
    },
  },
  servers: [
    {description: 'Xero Files API', url: 'https://api.xero.com/files.xro/1.0/'},
  ],
} as const
export default oasMeta
