// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    version: '3.0.1',
    title: 'Xero Payroll AU API',
    description: 'This is the Xero Payroll API for orgs in Australia region.',
    termsOfService:
      'https://developer.xero.com/xero-developer-platform-terms-conditions/',
    contact: {
      name: 'Xero Platform Team',
      email: 'api@xero.com',
      url: 'https://developer.xero.com',
    },
    license: {
      name: 'MIT',
      url: 'https://github.com/XeroAPI/Xero-OpenAPI/blob/master/LICENSE',
    },
  },
  servers: [
    {
      description: 'Xero Payroll AU API',
      url: 'https://api.xero.com/payroll.xro/1.0',
    },
  ],
} as const
export default oasMeta
