// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    contact: {email: 'integrations@salesloft.com', 'x-twitter': 'SalesLoft'},
    description:
      'SalesLoft helps transform sales teams into modern sales organizations  - converting more target accounts into customer accounts\n',
    title: 'SalesLoft Platform',
    version: 'v2',
    'x-apisguru-categories': ['customer_relation'],
    'x-logo': {
      url: 'https://api.apis.guru/v2/cache/logo/https_twitter.com_SalesLoft_profile_image.jpeg',
    },
    'x-origin': [
      {
        format: 'openapi',
        url: 'https://developers.salesloft.com/v2_api_def.json',
        version: '3.0',
      },
    ],
    'x-providerName': 'salesloft.com',
  },
  servers: [{url: 'https://api.salesloft.com'}],
} as const
export default oasMeta
