// This file is generated by @opensdks/cli, do not edit manually.
export const oasMeta = {
  info: {
    contact: {
      name: 'Slack developer relations',
      url: 'https://api.slack.com/support',
    },
    description:
      'One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.',
    title: 'Slack Web API',
    version: '1.7.0',
    'x-apisguru-categories': ['collaboration', 'messaging'],
    'x-logo': {
      url: 'https://api.apis.guru/v2/cache/logo/http_static.tumblr.com_wvuzcz9_LlKncfhmp_slack_logo_240.png',
    },
    'x-origin': [
      {
        format: 'openapi',
        url: 'https://raw.githubusercontent.com/slackapi/slack-api-specs/master/web-api/slack_web_openapi_v2.json',
        version: '3.0',
      },
    ],
    'x-providerName': 'slack.com',
  },
  servers: [{url: 'https://slack.com/api'}],
} as const
export default oasMeta
