// shebang not working for some reason... https://github.com/privatenumber/tsx/issues/440
// #!/usr/bin/env node --import tsx

import * as fs from 'node:fs'
import {parseArgs} from 'node:util'
import type {OpenAPI3} from 'openapi-typescript'
import openapiTS from 'openapi-typescript'
import prettier from 'prettier'
import R from 'remeda'
import type {OpenAPISpec} from '@opensdks/runtime'

async function prettyFormat(content: string) {
  return prettier.format(content, {
    ...(await import('../../prettier.config.js')).default,
    parser: 'typescript',
  })
}

export function generateMeta(oas: OpenAPISpec) {
  // TODO: Do some validation here.

  // const content = `
  //   export const info = ${JSON.stringify(oas.info ?? {})} as const

  //   export const servers = ${JSON.stringify(oas.servers ?? [])} as const
  // `
  const data = R.pick(oas, ['info', 'servers'])
  const content = `
  // This file is generated by @opensdks/cli, do not edit manually.
  export const oasMeta = ${JSON.stringify(data)} as const
  export default oasMeta
  `

  return content
}

export async function generateFromOas(oasPath: string) {
  const oas = JSON.parse(fs.readFileSync(oasPath, 'utf8')) as OpenAPISpec
  const meta = await prettyFormat(generateMeta(oas))
  const types = await prettyFormat(await openapiTS(oas as OpenAPI3))

  return {meta, types}
}

if (import.meta.url.includes(process.argv[1]!)) {
  const {
    positionals: [filename],
    values: {outName},
  } = parseArgs({
    options: {
      outName: {type: 'string', short: 'o'},
    },
    allowPositionals: true,
  })
  if (!filename) {
    throw new Error('You must specify a filename')
  }
  const ret = await generateFromOas(filename)

  if (outName) {
    fs.writeFileSync(outName + '.meta.ts', ret.meta)
    fs.writeFileSync(outName + '.d.ts', ret.types)
  } else {
    console.log(ret.meta)
    console.log(ret.types)
  }
}
