// shebang not working for some reason... https://github.com/privatenumber/tsx/issues/440
// #!/usr/bin/env node --import tsx

import * as fs from 'node:fs'
import type {OpenAPI3} from 'openapi-typescript'
import openapiTS from 'openapi-typescript'
import prettier from 'prettier'
import R from 'remeda'
import type {OpenAPISpec} from '@opensdks/runtime'

async function prettyFormat(content: string) {
  return prettier.format(content, {
    ...(await import('./prettier.config.js')).default,
    parser: 'typescript',
  })
}

export function generateMeta(oas: OpenAPISpec) {
  // TODO: Do some validation here.

  // const content = `
  //   export const info = ${JSON.stringify(oas.info ?? {})} as const

  //   export const servers = ${JSON.stringify(oas.servers ?? [])} as const
  // `
  const data = R.pick(oas, ['info', 'servers'])
  const content = `
  // This file is generated by @opensdks/cli, do not edit manually.
  export const oasMeta = ${JSON.stringify(data)} as const
  export default oasMeta
  `

  return content
}

export async function generateTypes(oas: OpenAPISpec) {
  const types = await openapiTS(oas as OpenAPI3)

  return `${types}

export interface oasTypes {
  components: components
  external: external
  operations: operations
  paths: paths
  webhooks: webhooks
}

export default oasTypes
`
}

export async function generateFromOas(oasPath: string) {
  const oas = JSON.parse(fs.readFileSync(oasPath, 'utf8')) as OpenAPISpec
  const meta = await prettyFormat(generateMeta(oas))

  const types = await generateTypes(oas)

  return {meta, types}
}
