/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/index.php/community/getRegionQueues': {
    post: operations['getRegionQueues']
  }
  '/index.php/community/activateRegion': {
    post: operations['activateRegion']
  }
}

export type webhooks = Record<string, never>

export interface components {
  schemas: never
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}

export type $defs = Record<string, never>

export type external = Record<string, never>

export interface operations {
  getRegionQueues: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': {
            status: number
            response: {
              message: {
                regions: {
                  regionId: string
                  name: string
                  neLat: string
                  neLng: string
                  swLat: string
                  swLng: string
                  includeDcFast: string
                  isDynamic: string
                  regionUntilTime: string
                  queueUntilTime: null
                  isActive: string
                  regionStatus: {
                    status: string
                  }
                  schedulerData: unknown[]
                  portQueue: unknown[]
                  stationNum: number
                  responsePending: {
                    deviceDetailId: string
                    deviceId: string
                    state: string
                  }
                }[]
                stationStatus: unknown[]
                mode: number
              }
            }
            stationStatus: unknown[]
          }
        }
      }
    }
  }
  activateRegion: {
    requestBody?: {
      content: {
        'application/json': unknown
      }
    }
    responses: {
      200: {
        content: {
          'application/json': Record<string, never>
        }
      }
    }
  }
}

export interface oasTypes {
  components: components
  external: external
  operations: operations
  paths: paths
  webhooks: webhooks
}

export default oasTypes
